###################################################################

# Created by write_sdc on Sat Jun 27 21:49:43 2026

###################################################################
set sdc_version 1.7

set_units -time ns -resistance kOhm -capacitance pF -voltage V -current mA
set_wire_load_mode top
set_wire_load_model -name ZeroWireload -library tcbn65gplustc_ccs
set_max_fanout 4 [current_design]
set_driving_cell -lib_cell INVD0 [get_ports {stage[2]}]
set_driving_cell -lib_cell INVD0 [get_ports {stage[1]}]
set_driving_cell -lib_cell INVD0 [get_ports {stage[0]}]
set_driving_cell -lib_cell INVD0 [get_ports {group[5]}]
set_driving_cell -lib_cell INVD0 [get_ports {group[4]}]
set_driving_cell -lib_cell INVD0 [get_ports {group[3]}]
set_driving_cell -lib_cell INVD0 [get_ports {group[2]}]
set_driving_cell -lib_cell INVD0 [get_ports {group[1]}]
set_driving_cell -lib_cell INVD0 [get_ports {group[0]}]
set_driving_cell -lib_cell INVD0 [get_ports {bfly[5]}]
set_driving_cell -lib_cell INVD0 [get_ports {bfly[4]}]
set_driving_cell -lib_cell INVD0 [get_ports {bfly[3]}]
set_driving_cell -lib_cell INVD0 [get_ports {bfly[2]}]
set_driving_cell -lib_cell INVD0 [get_ports {bfly[1]}]
set_driving_cell -lib_cell INVD0 [get_ports {bfly[0]}]
set_driving_cell -lib_cell INVD0 [get_ports {linear_addr[6]}]
set_driving_cell -lib_cell INVD0 [get_ports {linear_addr[5]}]
set_driving_cell -lib_cell INVD0 [get_ports {linear_addr[4]}]
set_driving_cell -lib_cell INVD0 [get_ports {linear_addr[3]}]
set_driving_cell -lib_cell INVD0 [get_ports {linear_addr[2]}]
set_driving_cell -lib_cell INVD0 [get_ports {linear_addr[1]}]
set_driving_cell -lib_cell INVD0 [get_ports {linear_addr[0]}]
set_load -pin_load 0.005 [get_ports {x0_addr[6]}]
set_load -pin_load 0.005 [get_ports {x0_addr[5]}]
set_load -pin_load 0.005 [get_ports {x0_addr[4]}]
set_load -pin_load 0.005 [get_ports {x0_addr[3]}]
set_load -pin_load 0.005 [get_ports {x0_addr[2]}]
set_load -pin_load 0.005 [get_ports {x0_addr[1]}]
set_load -pin_load 0.005 [get_ports {x0_addr[0]}]
set_load -pin_load 0.005 [get_ports {x1_addr[6]}]
set_load -pin_load 0.005 [get_ports {x1_addr[5]}]
set_load -pin_load 0.005 [get_ports {x1_addr[4]}]
set_load -pin_load 0.005 [get_ports {x1_addr[3]}]
set_load -pin_load 0.005 [get_ports {x1_addr[2]}]
set_load -pin_load 0.005 [get_ports {x1_addr[1]}]
set_load -pin_load 0.005 [get_ports {x1_addr[0]}]
set_load -pin_load 0.005 [get_ports {w_addr[5]}]
set_load -pin_load 0.005 [get_ports {w_addr[4]}]
set_load -pin_load 0.005 [get_ports {w_addr[3]}]
set_load -pin_load 0.005 [get_ports {w_addr[2]}]
set_load -pin_load 0.005 [get_ports {w_addr[1]}]
set_load -pin_load 0.005 [get_ports {w_addr[0]}]
set_load -pin_load 0.005 [get_ports {bitrev_addr[6]}]
set_load -pin_load 0.005 [get_ports {bitrev_addr[5]}]
set_load -pin_load 0.005 [get_ports {bitrev_addr[4]}]
set_load -pin_load 0.005 [get_ports {bitrev_addr[3]}]
set_load -pin_load 0.005 [get_ports {bitrev_addr[2]}]
set_load -pin_load 0.005 [get_ports {bitrev_addr[1]}]
set_load -pin_load 0.005 [get_ports {bitrev_addr[0]}]
set_max_capacitance 0.01 [get_ports {stage[2]}]
set_max_capacitance 0.01 [get_ports {stage[1]}]
set_max_capacitance 0.01 [get_ports {stage[0]}]
set_max_capacitance 0.01 [get_ports {group[5]}]
set_max_capacitance 0.01 [get_ports {group[4]}]
set_max_capacitance 0.01 [get_ports {group[3]}]
set_max_capacitance 0.01 [get_ports {group[2]}]
set_max_capacitance 0.01 [get_ports {group[1]}]
set_max_capacitance 0.01 [get_ports {group[0]}]
set_max_capacitance 0.01 [get_ports {bfly[5]}]
set_max_capacitance 0.01 [get_ports {bfly[4]}]
set_max_capacitance 0.01 [get_ports {bfly[3]}]
set_max_capacitance 0.01 [get_ports {bfly[2]}]
set_max_capacitance 0.01 [get_ports {bfly[1]}]
set_max_capacitance 0.01 [get_ports {bfly[0]}]
set_max_capacitance 0.01 [get_ports {linear_addr[6]}]
set_max_capacitance 0.01 [get_ports {linear_addr[5]}]
set_max_capacitance 0.01 [get_ports {linear_addr[4]}]
set_max_capacitance 0.01 [get_ports {linear_addr[3]}]
set_max_capacitance 0.01 [get_ports {linear_addr[2]}]
set_max_capacitance 0.01 [get_ports {linear_addr[1]}]
set_max_capacitance 0.01 [get_ports {linear_addr[0]}]
set_max_fanout 4 [get_ports {stage[2]}]
set_max_fanout 4 [get_ports {stage[1]}]
set_max_fanout 4 [get_ports {stage[0]}]
set_max_fanout 4 [get_ports {group[5]}]
set_max_fanout 4 [get_ports {group[4]}]
set_max_fanout 4 [get_ports {group[3]}]
set_max_fanout 4 [get_ports {group[2]}]
set_max_fanout 4 [get_ports {group[1]}]
set_max_fanout 4 [get_ports {group[0]}]
set_max_fanout 4 [get_ports {bfly[5]}]
set_max_fanout 4 [get_ports {bfly[4]}]
set_max_fanout 4 [get_ports {bfly[3]}]
set_max_fanout 4 [get_ports {bfly[2]}]
set_max_fanout 4 [get_ports {bfly[1]}]
set_max_fanout 4 [get_ports {bfly[0]}]
set_max_fanout 4 [get_ports {linear_addr[6]}]
set_max_fanout 4 [get_ports {linear_addr[5]}]
set_max_fanout 4 [get_ports {linear_addr[4]}]
set_max_fanout 4 [get_ports {linear_addr[3]}]
set_max_fanout 4 [get_ports {linear_addr[2]}]
set_max_fanout 4 [get_ports {linear_addr[1]}]
set_max_fanout 4 [get_ports {linear_addr[0]}]
create_clock -name vclk  -period 2  -waveform {0 1}
set_clock_uncertainty 0  [get_clocks vclk]
set_input_delay -clock vclk  0.1  [get_ports {stage[2]}]
set_input_delay -clock vclk  0.1  [get_ports {stage[1]}]
set_input_delay -clock vclk  0.1  [get_ports {stage[0]}]
set_input_delay -clock vclk  0.1  [get_ports {group[5]}]
set_input_delay -clock vclk  0.1  [get_ports {group[4]}]
set_input_delay -clock vclk  0.1  [get_ports {group[3]}]
set_input_delay -clock vclk  0.1  [get_ports {group[2]}]
set_input_delay -clock vclk  0.1  [get_ports {group[1]}]
set_input_delay -clock vclk  0.1  [get_ports {group[0]}]
set_input_delay -clock vclk  0.1  [get_ports {bfly[5]}]
set_input_delay -clock vclk  0.1  [get_ports {bfly[4]}]
set_input_delay -clock vclk  0.1  [get_ports {bfly[3]}]
set_input_delay -clock vclk  0.1  [get_ports {bfly[2]}]
set_input_delay -clock vclk  0.1  [get_ports {bfly[1]}]
set_input_delay -clock vclk  0.1  [get_ports {bfly[0]}]
set_input_delay -clock vclk  0.1  [get_ports {linear_addr[6]}]
set_input_delay -clock vclk  0.1  [get_ports {linear_addr[5]}]
set_input_delay -clock vclk  0.1  [get_ports {linear_addr[4]}]
set_input_delay -clock vclk  0.1  [get_ports {linear_addr[3]}]
set_input_delay -clock vclk  0.1  [get_ports {linear_addr[2]}]
set_input_delay -clock vclk  0.1  [get_ports {linear_addr[1]}]
set_input_delay -clock vclk  0.1  [get_ports {linear_addr[0]}]
set_output_delay -clock vclk  0.05  [get_ports {x0_addr[6]}]
set_output_delay -clock vclk  0.05  [get_ports {x0_addr[5]}]
set_output_delay -clock vclk  0.05  [get_ports {x0_addr[4]}]
set_output_delay -clock vclk  0.05  [get_ports {x0_addr[3]}]
set_output_delay -clock vclk  0.05  [get_ports {x0_addr[2]}]
set_output_delay -clock vclk  0.05  [get_ports {x0_addr[1]}]
set_output_delay -clock vclk  0.05  [get_ports {x0_addr[0]}]
set_output_delay -clock vclk  0.05  [get_ports {x1_addr[6]}]
set_output_delay -clock vclk  0.05  [get_ports {x1_addr[5]}]
set_output_delay -clock vclk  0.05  [get_ports {x1_addr[4]}]
set_output_delay -clock vclk  0.05  [get_ports {x1_addr[3]}]
set_output_delay -clock vclk  0.05  [get_ports {x1_addr[2]}]
set_output_delay -clock vclk  0.05  [get_ports {x1_addr[1]}]
set_output_delay -clock vclk  0.05  [get_ports {x1_addr[0]}]
set_output_delay -clock vclk  0.05  [get_ports {w_addr[5]}]
set_output_delay -clock vclk  0.05  [get_ports {w_addr[4]}]
set_output_delay -clock vclk  0.05  [get_ports {w_addr[3]}]
set_output_delay -clock vclk  0.05  [get_ports {w_addr[2]}]
set_output_delay -clock vclk  0.05  [get_ports {w_addr[1]}]
set_output_delay -clock vclk  0.05  [get_ports {w_addr[0]}]
set_output_delay -clock vclk  0.05  [get_ports {bitrev_addr[6]}]
set_output_delay -clock vclk  0.05  [get_ports {bitrev_addr[5]}]
set_output_delay -clock vclk  0.05  [get_ports {bitrev_addr[4]}]
set_output_delay -clock vclk  0.05  [get_ports {bitrev_addr[3]}]
set_output_delay -clock vclk  0.05  [get_ports {bitrev_addr[2]}]
set_output_delay -clock vclk  0.05  [get_ports {bitrev_addr[1]}]
set_output_delay -clock vclk  0.05  [get_ports {bitrev_addr[0]}]
