###################################################################

# Created by write_sdc on Sat Jun 27 17:50:06 2026

###################################################################
set sdc_version 2.1

set_units -time ns -resistance kOhm -capacitance pF -voltage V -current mA
set_max_fanout 4 [current_design]
set_driving_cell -lib_cell INVD0 [get_ports clk]
set_driving_cell -lib_cell INVD0 [get_ports cen]
set_driving_cell -lib_cell INVD0 [get_ports wen]
set_driving_cell -lib_cell INVD0 [get_ports {addr[8]}]
set_driving_cell -lib_cell INVD0 [get_ports {addr[7]}]
set_driving_cell -lib_cell INVD0 [get_ports {addr[6]}]
set_driving_cell -lib_cell INVD0 [get_ports {addr[5]}]
set_driving_cell -lib_cell INVD0 [get_ports {addr[4]}]
set_driving_cell -lib_cell INVD0 [get_ports {addr[3]}]
set_driving_cell -lib_cell INVD0 [get_ports {addr[2]}]
set_driving_cell -lib_cell INVD0 [get_ports {addr[1]}]
set_driving_cell -lib_cell INVD0 [get_ports {addr[0]}]
set_driving_cell -lib_cell INVD0 [get_ports {din[31]}]
set_driving_cell -lib_cell INVD0 [get_ports {din[30]}]
set_driving_cell -lib_cell INVD0 [get_ports {din[29]}]
set_driving_cell -lib_cell INVD0 [get_ports {din[28]}]
set_driving_cell -lib_cell INVD0 [get_ports {din[27]}]
set_driving_cell -lib_cell INVD0 [get_ports {din[26]}]
set_driving_cell -lib_cell INVD0 [get_ports {din[25]}]
set_driving_cell -lib_cell INVD0 [get_ports {din[24]}]
set_driving_cell -lib_cell INVD0 [get_ports {din[23]}]
set_driving_cell -lib_cell INVD0 [get_ports {din[22]}]
set_driving_cell -lib_cell INVD0 [get_ports {din[21]}]
set_driving_cell -lib_cell INVD0 [get_ports {din[20]}]
set_driving_cell -lib_cell INVD0 [get_ports {din[19]}]
set_driving_cell -lib_cell INVD0 [get_ports {din[18]}]
set_driving_cell -lib_cell INVD0 [get_ports {din[17]}]
set_driving_cell -lib_cell INVD0 [get_ports {din[16]}]
set_driving_cell -lib_cell INVD0 [get_ports {din[15]}]
set_driving_cell -lib_cell INVD0 [get_ports {din[14]}]
set_driving_cell -lib_cell INVD0 [get_ports {din[13]}]
set_driving_cell -lib_cell INVD0 [get_ports {din[12]}]
set_driving_cell -lib_cell INVD0 [get_ports {din[11]}]
set_driving_cell -lib_cell INVD0 [get_ports {din[10]}]
set_driving_cell -lib_cell INVD0 [get_ports {din[9]}]
set_driving_cell -lib_cell INVD0 [get_ports {din[8]}]
set_driving_cell -lib_cell INVD0 [get_ports {din[7]}]
set_driving_cell -lib_cell INVD0 [get_ports {din[6]}]
set_driving_cell -lib_cell INVD0 [get_ports {din[5]}]
set_driving_cell -lib_cell INVD0 [get_ports {din[4]}]
set_driving_cell -lib_cell INVD0 [get_ports {din[3]}]
set_driving_cell -lib_cell INVD0 [get_ports {din[2]}]
set_driving_cell -lib_cell INVD0 [get_ports {din[1]}]
set_driving_cell -lib_cell INVD0 [get_ports {din[0]}]
set_load -pin_load 0.005 [get_ports {dout[31]}]
set_load -pin_load 0.005 [get_ports {dout[30]}]
set_load -pin_load 0.005 [get_ports {dout[29]}]
set_load -pin_load 0.005 [get_ports {dout[28]}]
set_load -pin_load 0.005 [get_ports {dout[27]}]
set_load -pin_load 0.005 [get_ports {dout[26]}]
set_load -pin_load 0.005 [get_ports {dout[25]}]
set_load -pin_load 0.005 [get_ports {dout[24]}]
set_load -pin_load 0.005 [get_ports {dout[23]}]
set_load -pin_load 0.005 [get_ports {dout[22]}]
set_load -pin_load 0.005 [get_ports {dout[21]}]
set_load -pin_load 0.005 [get_ports {dout[20]}]
set_load -pin_load 0.005 [get_ports {dout[19]}]
set_load -pin_load 0.005 [get_ports {dout[18]}]
set_load -pin_load 0.005 [get_ports {dout[17]}]
set_load -pin_load 0.005 [get_ports {dout[16]}]
set_load -pin_load 0.005 [get_ports {dout[15]}]
set_load -pin_load 0.005 [get_ports {dout[14]}]
set_load -pin_load 0.005 [get_ports {dout[13]}]
set_load -pin_load 0.005 [get_ports {dout[12]}]
set_load -pin_load 0.005 [get_ports {dout[11]}]
set_load -pin_load 0.005 [get_ports {dout[10]}]
set_load -pin_load 0.005 [get_ports {dout[9]}]
set_load -pin_load 0.005 [get_ports {dout[8]}]
set_load -pin_load 0.005 [get_ports {dout[7]}]
set_load -pin_load 0.005 [get_ports {dout[6]}]
set_load -pin_load 0.005 [get_ports {dout[5]}]
set_load -pin_load 0.005 [get_ports {dout[4]}]
set_load -pin_load 0.005 [get_ports {dout[3]}]
set_load -pin_load 0.005 [get_ports {dout[2]}]
set_load -pin_load 0.005 [get_ports {dout[1]}]
set_load -pin_load 0.005 [get_ports {dout[0]}]
set_max_capacitance 0.005 [get_ports clk]
set_max_capacitance 0.005 [get_ports cen]
set_max_capacitance 0.005 [get_ports wen]
set_max_capacitance 0.005 [get_ports {addr[8]}]
set_max_capacitance 0.005 [get_ports {addr[7]}]
set_max_capacitance 0.005 [get_ports {addr[6]}]
set_max_capacitance 0.005 [get_ports {addr[5]}]
set_max_capacitance 0.005 [get_ports {addr[4]}]
set_max_capacitance 0.005 [get_ports {addr[3]}]
set_max_capacitance 0.005 [get_ports {addr[2]}]
set_max_capacitance 0.005 [get_ports {addr[1]}]
set_max_capacitance 0.005 [get_ports {addr[0]}]
set_max_capacitance 0.005 [get_ports {din[31]}]
set_max_capacitance 0.005 [get_ports {din[30]}]
set_max_capacitance 0.005 [get_ports {din[29]}]
set_max_capacitance 0.005 [get_ports {din[28]}]
set_max_capacitance 0.005 [get_ports {din[27]}]
set_max_capacitance 0.005 [get_ports {din[26]}]
set_max_capacitance 0.005 [get_ports {din[25]}]
set_max_capacitance 0.005 [get_ports {din[24]}]
set_max_capacitance 0.005 [get_ports {din[23]}]
set_max_capacitance 0.005 [get_ports {din[22]}]
set_max_capacitance 0.005 [get_ports {din[21]}]
set_max_capacitance 0.005 [get_ports {din[20]}]
set_max_capacitance 0.005 [get_ports {din[19]}]
set_max_capacitance 0.005 [get_ports {din[18]}]
set_max_capacitance 0.005 [get_ports {din[17]}]
set_max_capacitance 0.005 [get_ports {din[16]}]
set_max_capacitance 0.005 [get_ports {din[15]}]
set_max_capacitance 0.005 [get_ports {din[14]}]
set_max_capacitance 0.005 [get_ports {din[13]}]
set_max_capacitance 0.005 [get_ports {din[12]}]
set_max_capacitance 0.005 [get_ports {din[11]}]
set_max_capacitance 0.005 [get_ports {din[10]}]
set_max_capacitance 0.005 [get_ports {din[9]}]
set_max_capacitance 0.005 [get_ports {din[8]}]
set_max_capacitance 0.005 [get_ports {din[7]}]
set_max_capacitance 0.005 [get_ports {din[6]}]
set_max_capacitance 0.005 [get_ports {din[5]}]
set_max_capacitance 0.005 [get_ports {din[4]}]
set_max_capacitance 0.005 [get_ports {din[3]}]
set_max_capacitance 0.005 [get_ports {din[2]}]
set_max_capacitance 0.005 [get_ports {din[1]}]
set_max_capacitance 0.005 [get_ports {din[0]}]
set_max_fanout 4 [get_ports clk]
set_max_fanout 4 [get_ports cen]
set_max_fanout 4 [get_ports wen]
set_max_fanout 4 [get_ports {addr[8]}]
set_max_fanout 4 [get_ports {addr[7]}]
set_max_fanout 4 [get_ports {addr[6]}]
set_max_fanout 4 [get_ports {addr[5]}]
set_max_fanout 4 [get_ports {addr[4]}]
set_max_fanout 4 [get_ports {addr[3]}]
set_max_fanout 4 [get_ports {addr[2]}]
set_max_fanout 4 [get_ports {addr[1]}]
set_max_fanout 4 [get_ports {addr[0]}]
set_max_fanout 4 [get_ports {din[31]}]
set_max_fanout 4 [get_ports {din[30]}]
set_max_fanout 4 [get_ports {din[29]}]
set_max_fanout 4 [get_ports {din[28]}]
set_max_fanout 4 [get_ports {din[27]}]
set_max_fanout 4 [get_ports {din[26]}]
set_max_fanout 4 [get_ports {din[25]}]
set_max_fanout 4 [get_ports {din[24]}]
set_max_fanout 4 [get_ports {din[23]}]
set_max_fanout 4 [get_ports {din[22]}]
set_max_fanout 4 [get_ports {din[21]}]
set_max_fanout 4 [get_ports {din[20]}]
set_max_fanout 4 [get_ports {din[19]}]
set_max_fanout 4 [get_ports {din[18]}]
set_max_fanout 4 [get_ports {din[17]}]
set_max_fanout 4 [get_ports {din[16]}]
set_max_fanout 4 [get_ports {din[15]}]
set_max_fanout 4 [get_ports {din[14]}]
set_max_fanout 4 [get_ports {din[13]}]
set_max_fanout 4 [get_ports {din[12]}]
set_max_fanout 4 [get_ports {din[11]}]
set_max_fanout 4 [get_ports {din[10]}]
set_max_fanout 4 [get_ports {din[9]}]
set_max_fanout 4 [get_ports {din[8]}]
set_max_fanout 4 [get_ports {din[7]}]
set_max_fanout 4 [get_ports {din[6]}]
set_max_fanout 4 [get_ports {din[5]}]
set_max_fanout 4 [get_ports {din[4]}]
set_max_fanout 4 [get_ports {din[3]}]
set_max_fanout 4 [get_ports {din[2]}]
set_max_fanout 4 [get_ports {din[1]}]
set_max_fanout 4 [get_ports {din[0]}]
set_ideal_network [get_ports clk]
create_clock [get_ports clk]  -period 2  -waveform {0 1}
set_clock_uncertainty 0  [get_clocks clk]
set_clock_transition -max -rise 0.04 [get_clocks clk]
set_clock_transition -max -fall 0.04 [get_clocks clk]
set_clock_transition -min -rise 0.04 [get_clocks clk]
set_clock_transition -min -fall 0.04 [get_clocks clk]
set_input_delay -clock clk  0.05  [get_ports cen]
set_input_delay -clock clk  0.05  [get_ports wen]
set_input_delay -clock clk  0.05  [get_ports {addr[8]}]
set_input_delay -clock clk  0.05  [get_ports {addr[7]}]
set_input_delay -clock clk  0.05  [get_ports {addr[6]}]
set_input_delay -clock clk  0.05  [get_ports {addr[5]}]
set_input_delay -clock clk  0.05  [get_ports {addr[4]}]
set_input_delay -clock clk  0.05  [get_ports {addr[3]}]
set_input_delay -clock clk  0.05  [get_ports {addr[2]}]
set_input_delay -clock clk  0.05  [get_ports {addr[1]}]
set_input_delay -clock clk  0.05  [get_ports {addr[0]}]
set_input_delay -clock clk  0.05  [get_ports {din[31]}]
set_input_delay -clock clk  0.05  [get_ports {din[30]}]
set_input_delay -clock clk  0.05  [get_ports {din[29]}]
set_input_delay -clock clk  0.05  [get_ports {din[28]}]
set_input_delay -clock clk  0.05  [get_ports {din[27]}]
set_input_delay -clock clk  0.05  [get_ports {din[26]}]
set_input_delay -clock clk  0.05  [get_ports {din[25]}]
set_input_delay -clock clk  0.05  [get_ports {din[24]}]
set_input_delay -clock clk  0.05  [get_ports {din[23]}]
set_input_delay -clock clk  0.05  [get_ports {din[22]}]
set_input_delay -clock clk  0.05  [get_ports {din[21]}]
set_input_delay -clock clk  0.05  [get_ports {din[20]}]
set_input_delay -clock clk  0.05  [get_ports {din[19]}]
set_input_delay -clock clk  0.05  [get_ports {din[18]}]
set_input_delay -clock clk  0.05  [get_ports {din[17]}]
set_input_delay -clock clk  0.05  [get_ports {din[16]}]
set_input_delay -clock clk  0.05  [get_ports {din[15]}]
set_input_delay -clock clk  0.05  [get_ports {din[14]}]
set_input_delay -clock clk  0.05  [get_ports {din[13]}]
set_input_delay -clock clk  0.05  [get_ports {din[12]}]
set_input_delay -clock clk  0.05  [get_ports {din[11]}]
set_input_delay -clock clk  0.05  [get_ports {din[10]}]
set_input_delay -clock clk  0.05  [get_ports {din[9]}]
set_input_delay -clock clk  0.05  [get_ports {din[8]}]
set_input_delay -clock clk  0.05  [get_ports {din[7]}]
set_input_delay -clock clk  0.05  [get_ports {din[6]}]
set_input_delay -clock clk  0.05  [get_ports {din[5]}]
set_input_delay -clock clk  0.05  [get_ports {din[4]}]
set_input_delay -clock clk  0.05  [get_ports {din[3]}]
set_input_delay -clock clk  0.05  [get_ports {din[2]}]
set_input_delay -clock clk  0.05  [get_ports {din[1]}]
set_input_delay -clock clk  0.05  [get_ports {din[0]}]
set_output_delay -clock clk  0.05  [get_ports {dout[31]}]
set_output_delay -clock clk  0.05  [get_ports {dout[30]}]
set_output_delay -clock clk  0.05  [get_ports {dout[29]}]
set_output_delay -clock clk  0.05  [get_ports {dout[28]}]
set_output_delay -clock clk  0.05  [get_ports {dout[27]}]
set_output_delay -clock clk  0.05  [get_ports {dout[26]}]
set_output_delay -clock clk  0.05  [get_ports {dout[25]}]
set_output_delay -clock clk  0.05  [get_ports {dout[24]}]
set_output_delay -clock clk  0.05  [get_ports {dout[23]}]
set_output_delay -clock clk  0.05  [get_ports {dout[22]}]
set_output_delay -clock clk  0.05  [get_ports {dout[21]}]
set_output_delay -clock clk  0.05  [get_ports {dout[20]}]
set_output_delay -clock clk  0.05  [get_ports {dout[19]}]
set_output_delay -clock clk  0.05  [get_ports {dout[18]}]
set_output_delay -clock clk  0.05  [get_ports {dout[17]}]
set_output_delay -clock clk  0.05  [get_ports {dout[16]}]
set_output_delay -clock clk  0.05  [get_ports {dout[15]}]
set_output_delay -clock clk  0.05  [get_ports {dout[14]}]
set_output_delay -clock clk  0.05  [get_ports {dout[13]}]
set_output_delay -clock clk  0.05  [get_ports {dout[12]}]
set_output_delay -clock clk  0.05  [get_ports {dout[11]}]
set_output_delay -clock clk  0.05  [get_ports {dout[10]}]
set_output_delay -clock clk  0.05  [get_ports {dout[9]}]
set_output_delay -clock clk  0.05  [get_ports {dout[8]}]
set_output_delay -clock clk  0.05  [get_ports {dout[7]}]
set_output_delay -clock clk  0.05  [get_ports {dout[6]}]
set_output_delay -clock clk  0.05  [get_ports {dout[5]}]
set_output_delay -clock clk  0.05  [get_ports {dout[4]}]
set_output_delay -clock clk  0.05  [get_ports {dout[3]}]
set_output_delay -clock clk  0.05  [get_ports {dout[2]}]
set_output_delay -clock clk  0.05  [get_ports {dout[1]}]
set_output_delay -clock clk  0.05  [get_ports {dout[0]}]
