###################################################################

# Created by write_sdc on Sat Jun 27 21:14:51 2026

###################################################################
set sdc_version 1.7

set_units -time ns -resistance kOhm -capacitance pF -voltage V -current mA
set_wire_load_mode top
set_wire_load_model -name ZeroWireload -library tcbn65gplustc_ccs
set_max_fanout 4 [current_design]
set_driving_cell -lib_cell INVD0 [get_ports clk]
set_driving_cell -lib_cell INVD0 [get_ports rstn]
set_driving_cell -lib_cell INVD0 [get_ports start]
set_driving_cell -lib_cell INVD0 [get_ports {x0[15]}]
set_driving_cell -lib_cell INVD0 [get_ports {x0[14]}]
set_driving_cell -lib_cell INVD0 [get_ports {x0[13]}]
set_driving_cell -lib_cell INVD0 [get_ports {x0[12]}]
set_driving_cell -lib_cell INVD0 [get_ports {x0[11]}]
set_driving_cell -lib_cell INVD0 [get_ports {x0[10]}]
set_driving_cell -lib_cell INVD0 [get_ports {x0[9]}]
set_driving_cell -lib_cell INVD0 [get_ports {x0[8]}]
set_driving_cell -lib_cell INVD0 [get_ports {x0[7]}]
set_driving_cell -lib_cell INVD0 [get_ports {x0[6]}]
set_driving_cell -lib_cell INVD0 [get_ports {x0[5]}]
set_driving_cell -lib_cell INVD0 [get_ports {x0[4]}]
set_driving_cell -lib_cell INVD0 [get_ports {x0[3]}]
set_driving_cell -lib_cell INVD0 [get_ports {x0[2]}]
set_driving_cell -lib_cell INVD0 [get_ports {x0[1]}]
set_driving_cell -lib_cell INVD0 [get_ports {x0[0]}]
set_driving_cell -lib_cell INVD0 [get_ports {x1[15]}]
set_driving_cell -lib_cell INVD0 [get_ports {x1[14]}]
set_driving_cell -lib_cell INVD0 [get_ports {x1[13]}]
set_driving_cell -lib_cell INVD0 [get_ports {x1[12]}]
set_driving_cell -lib_cell INVD0 [get_ports {x1[11]}]
set_driving_cell -lib_cell INVD0 [get_ports {x1[10]}]
set_driving_cell -lib_cell INVD0 [get_ports {x1[9]}]
set_driving_cell -lib_cell INVD0 [get_ports {x1[8]}]
set_driving_cell -lib_cell INVD0 [get_ports {x1[7]}]
set_driving_cell -lib_cell INVD0 [get_ports {x1[6]}]
set_driving_cell -lib_cell INVD0 [get_ports {x1[5]}]
set_driving_cell -lib_cell INVD0 [get_ports {x1[4]}]
set_driving_cell -lib_cell INVD0 [get_ports {x1[3]}]
set_driving_cell -lib_cell INVD0 [get_ports {x1[2]}]
set_driving_cell -lib_cell INVD0 [get_ports {x1[1]}]
set_driving_cell -lib_cell INVD0 [get_ports {x1[0]}]
set_driving_cell -lib_cell INVD0 [get_ports {w[15]}]
set_driving_cell -lib_cell INVD0 [get_ports {w[14]}]
set_driving_cell -lib_cell INVD0 [get_ports {w[13]}]
set_driving_cell -lib_cell INVD0 [get_ports {w[12]}]
set_driving_cell -lib_cell INVD0 [get_ports {w[11]}]
set_driving_cell -lib_cell INVD0 [get_ports {w[10]}]
set_driving_cell -lib_cell INVD0 [get_ports {w[9]}]
set_driving_cell -lib_cell INVD0 [get_ports {w[8]}]
set_driving_cell -lib_cell INVD0 [get_ports {w[7]}]
set_driving_cell -lib_cell INVD0 [get_ports {w[6]}]
set_driving_cell -lib_cell INVD0 [get_ports {w[5]}]
set_driving_cell -lib_cell INVD0 [get_ports {w[4]}]
set_driving_cell -lib_cell INVD0 [get_ports {w[3]}]
set_driving_cell -lib_cell INVD0 [get_ports {w[2]}]
set_driving_cell -lib_cell INVD0 [get_ports {w[1]}]
set_driving_cell -lib_cell INVD0 [get_ports {w[0]}]
set_load -pin_load 0.005 [get_ports {x0_out[15]}]
set_load -pin_load 0.005 [get_ports {x0_out[14]}]
set_load -pin_load 0.005 [get_ports {x0_out[13]}]
set_load -pin_load 0.005 [get_ports {x0_out[12]}]
set_load -pin_load 0.005 [get_ports {x0_out[11]}]
set_load -pin_load 0.005 [get_ports {x0_out[10]}]
set_load -pin_load 0.005 [get_ports {x0_out[9]}]
set_load -pin_load 0.005 [get_ports {x0_out[8]}]
set_load -pin_load 0.005 [get_ports {x0_out[7]}]
set_load -pin_load 0.005 [get_ports {x0_out[6]}]
set_load -pin_load 0.005 [get_ports {x0_out[5]}]
set_load -pin_load 0.005 [get_ports {x0_out[4]}]
set_load -pin_load 0.005 [get_ports {x0_out[3]}]
set_load -pin_load 0.005 [get_ports {x0_out[2]}]
set_load -pin_load 0.005 [get_ports {x0_out[1]}]
set_load -pin_load 0.005 [get_ports {x0_out[0]}]
set_load -pin_load 0.005 [get_ports {x1_out[15]}]
set_load -pin_load 0.005 [get_ports {x1_out[14]}]
set_load -pin_load 0.005 [get_ports {x1_out[13]}]
set_load -pin_load 0.005 [get_ports {x1_out[12]}]
set_load -pin_load 0.005 [get_ports {x1_out[11]}]
set_load -pin_load 0.005 [get_ports {x1_out[10]}]
set_load -pin_load 0.005 [get_ports {x1_out[9]}]
set_load -pin_load 0.005 [get_ports {x1_out[8]}]
set_load -pin_load 0.005 [get_ports {x1_out[7]}]
set_load -pin_load 0.005 [get_ports {x1_out[6]}]
set_load -pin_load 0.005 [get_ports {x1_out[5]}]
set_load -pin_load 0.005 [get_ports {x1_out[4]}]
set_load -pin_load 0.005 [get_ports {x1_out[3]}]
set_load -pin_load 0.005 [get_ports {x1_out[2]}]
set_load -pin_load 0.005 [get_ports {x1_out[1]}]
set_load -pin_load 0.005 [get_ports {x1_out[0]}]
set_load -pin_load 0.005 [get_ports done]
set_max_capacitance 0.01 [get_ports clk]
set_max_capacitance 0.01 [get_ports rstn]
set_max_capacitance 0.01 [get_ports start]
set_max_capacitance 0.01 [get_ports {x0[15]}]
set_max_capacitance 0.01 [get_ports {x0[14]}]
set_max_capacitance 0.01 [get_ports {x0[13]}]
set_max_capacitance 0.01 [get_ports {x0[12]}]
set_max_capacitance 0.01 [get_ports {x0[11]}]
set_max_capacitance 0.01 [get_ports {x0[10]}]
set_max_capacitance 0.01 [get_ports {x0[9]}]
set_max_capacitance 0.01 [get_ports {x0[8]}]
set_max_capacitance 0.01 [get_ports {x0[7]}]
set_max_capacitance 0.01 [get_ports {x0[6]}]
set_max_capacitance 0.01 [get_ports {x0[5]}]
set_max_capacitance 0.01 [get_ports {x0[4]}]
set_max_capacitance 0.01 [get_ports {x0[3]}]
set_max_capacitance 0.01 [get_ports {x0[2]}]
set_max_capacitance 0.01 [get_ports {x0[1]}]
set_max_capacitance 0.01 [get_ports {x0[0]}]
set_max_capacitance 0.01 [get_ports {x1[15]}]
set_max_capacitance 0.01 [get_ports {x1[14]}]
set_max_capacitance 0.01 [get_ports {x1[13]}]
set_max_capacitance 0.01 [get_ports {x1[12]}]
set_max_capacitance 0.01 [get_ports {x1[11]}]
set_max_capacitance 0.01 [get_ports {x1[10]}]
set_max_capacitance 0.01 [get_ports {x1[9]}]
set_max_capacitance 0.01 [get_ports {x1[8]}]
set_max_capacitance 0.01 [get_ports {x1[7]}]
set_max_capacitance 0.01 [get_ports {x1[6]}]
set_max_capacitance 0.01 [get_ports {x1[5]}]
set_max_capacitance 0.01 [get_ports {x1[4]}]
set_max_capacitance 0.01 [get_ports {x1[3]}]
set_max_capacitance 0.01 [get_ports {x1[2]}]
set_max_capacitance 0.01 [get_ports {x1[1]}]
set_max_capacitance 0.01 [get_ports {x1[0]}]
set_max_capacitance 0.01 [get_ports {w[15]}]
set_max_capacitance 0.01 [get_ports {w[14]}]
set_max_capacitance 0.01 [get_ports {w[13]}]
set_max_capacitance 0.01 [get_ports {w[12]}]
set_max_capacitance 0.01 [get_ports {w[11]}]
set_max_capacitance 0.01 [get_ports {w[10]}]
set_max_capacitance 0.01 [get_ports {w[9]}]
set_max_capacitance 0.01 [get_ports {w[8]}]
set_max_capacitance 0.01 [get_ports {w[7]}]
set_max_capacitance 0.01 [get_ports {w[6]}]
set_max_capacitance 0.01 [get_ports {w[5]}]
set_max_capacitance 0.01 [get_ports {w[4]}]
set_max_capacitance 0.01 [get_ports {w[3]}]
set_max_capacitance 0.01 [get_ports {w[2]}]
set_max_capacitance 0.01 [get_ports {w[1]}]
set_max_capacitance 0.01 [get_ports {w[0]}]
set_max_fanout 4 [get_ports clk]
set_max_fanout 4 [get_ports rstn]
set_max_fanout 4 [get_ports start]
set_max_fanout 4 [get_ports {x0[15]}]
set_max_fanout 4 [get_ports {x0[14]}]
set_max_fanout 4 [get_ports {x0[13]}]
set_max_fanout 4 [get_ports {x0[12]}]
set_max_fanout 4 [get_ports {x0[11]}]
set_max_fanout 4 [get_ports {x0[10]}]
set_max_fanout 4 [get_ports {x0[9]}]
set_max_fanout 4 [get_ports {x0[8]}]
set_max_fanout 4 [get_ports {x0[7]}]
set_max_fanout 4 [get_ports {x0[6]}]
set_max_fanout 4 [get_ports {x0[5]}]
set_max_fanout 4 [get_ports {x0[4]}]
set_max_fanout 4 [get_ports {x0[3]}]
set_max_fanout 4 [get_ports {x0[2]}]
set_max_fanout 4 [get_ports {x0[1]}]
set_max_fanout 4 [get_ports {x0[0]}]
set_max_fanout 4 [get_ports {x1[15]}]
set_max_fanout 4 [get_ports {x1[14]}]
set_max_fanout 4 [get_ports {x1[13]}]
set_max_fanout 4 [get_ports {x1[12]}]
set_max_fanout 4 [get_ports {x1[11]}]
set_max_fanout 4 [get_ports {x1[10]}]
set_max_fanout 4 [get_ports {x1[9]}]
set_max_fanout 4 [get_ports {x1[8]}]
set_max_fanout 4 [get_ports {x1[7]}]
set_max_fanout 4 [get_ports {x1[6]}]
set_max_fanout 4 [get_ports {x1[5]}]
set_max_fanout 4 [get_ports {x1[4]}]
set_max_fanout 4 [get_ports {x1[3]}]
set_max_fanout 4 [get_ports {x1[2]}]
set_max_fanout 4 [get_ports {x1[1]}]
set_max_fanout 4 [get_ports {x1[0]}]
set_max_fanout 4 [get_ports {w[15]}]
set_max_fanout 4 [get_ports {w[14]}]
set_max_fanout 4 [get_ports {w[13]}]
set_max_fanout 4 [get_ports {w[12]}]
set_max_fanout 4 [get_ports {w[11]}]
set_max_fanout 4 [get_ports {w[10]}]
set_max_fanout 4 [get_ports {w[9]}]
set_max_fanout 4 [get_ports {w[8]}]
set_max_fanout 4 [get_ports {w[7]}]
set_max_fanout 4 [get_ports {w[6]}]
set_max_fanout 4 [get_ports {w[5]}]
set_max_fanout 4 [get_ports {w[4]}]
set_max_fanout 4 [get_ports {w[3]}]
set_max_fanout 4 [get_ports {w[2]}]
set_max_fanout 4 [get_ports {w[1]}]
set_max_fanout 4 [get_ports {w[0]}]
create_clock [get_ports clk]  -period 4  -waveform {0 2}
set_clock_uncertainty 0  [get_clocks clk]
set_clock_transition -max -rise 0.05 [get_clocks clk]
set_clock_transition -max -fall 0.05 [get_clocks clk]
set_clock_transition -min -rise 0.05 [get_clocks clk]
set_clock_transition -min -fall 0.05 [get_clocks clk]
set_input_delay -clock clk  0.1  [get_ports rstn]
set_input_delay -clock clk  0.1  [get_ports start]
set_input_delay -clock clk  0.1  [get_ports {x0[15]}]
set_input_delay -clock clk  0.1  [get_ports {x0[14]}]
set_input_delay -clock clk  0.1  [get_ports {x0[13]}]
set_input_delay -clock clk  0.1  [get_ports {x0[12]}]
set_input_delay -clock clk  0.1  [get_ports {x0[11]}]
set_input_delay -clock clk  0.1  [get_ports {x0[10]}]
set_input_delay -clock clk  0.1  [get_ports {x0[9]}]
set_input_delay -clock clk  0.1  [get_ports {x0[8]}]
set_input_delay -clock clk  0.1  [get_ports {x0[7]}]
set_input_delay -clock clk  0.1  [get_ports {x0[6]}]
set_input_delay -clock clk  0.1  [get_ports {x0[5]}]
set_input_delay -clock clk  0.1  [get_ports {x0[4]}]
set_input_delay -clock clk  0.1  [get_ports {x0[3]}]
set_input_delay -clock clk  0.1  [get_ports {x0[2]}]
set_input_delay -clock clk  0.1  [get_ports {x0[1]}]
set_input_delay -clock clk  0.1  [get_ports {x0[0]}]
set_input_delay -clock clk  0.1  [get_ports {x1[15]}]
set_input_delay -clock clk  0.1  [get_ports {x1[14]}]
set_input_delay -clock clk  0.1  [get_ports {x1[13]}]
set_input_delay -clock clk  0.1  [get_ports {x1[12]}]
set_input_delay -clock clk  0.1  [get_ports {x1[11]}]
set_input_delay -clock clk  0.1  [get_ports {x1[10]}]
set_input_delay -clock clk  0.1  [get_ports {x1[9]}]
set_input_delay -clock clk  0.1  [get_ports {x1[8]}]
set_input_delay -clock clk  0.1  [get_ports {x1[7]}]
set_input_delay -clock clk  0.1  [get_ports {x1[6]}]
set_input_delay -clock clk  0.1  [get_ports {x1[5]}]
set_input_delay -clock clk  0.1  [get_ports {x1[4]}]
set_input_delay -clock clk  0.1  [get_ports {x1[3]}]
set_input_delay -clock clk  0.1  [get_ports {x1[2]}]
set_input_delay -clock clk  0.1  [get_ports {x1[1]}]
set_input_delay -clock clk  0.1  [get_ports {x1[0]}]
set_input_delay -clock clk  0.1  [get_ports {w[15]}]
set_input_delay -clock clk  0.1  [get_ports {w[14]}]
set_input_delay -clock clk  0.1  [get_ports {w[13]}]
set_input_delay -clock clk  0.1  [get_ports {w[12]}]
set_input_delay -clock clk  0.1  [get_ports {w[11]}]
set_input_delay -clock clk  0.1  [get_ports {w[10]}]
set_input_delay -clock clk  0.1  [get_ports {w[9]}]
set_input_delay -clock clk  0.1  [get_ports {w[8]}]
set_input_delay -clock clk  0.1  [get_ports {w[7]}]
set_input_delay -clock clk  0.1  [get_ports {w[6]}]
set_input_delay -clock clk  0.1  [get_ports {w[5]}]
set_input_delay -clock clk  0.1  [get_ports {w[4]}]
set_input_delay -clock clk  0.1  [get_ports {w[3]}]
set_input_delay -clock clk  0.1  [get_ports {w[2]}]
set_input_delay -clock clk  0.1  [get_ports {w[1]}]
set_input_delay -clock clk  0.1  [get_ports {w[0]}]
set_output_delay -clock clk  0.05  [get_ports {x0_out[15]}]
set_output_delay -clock clk  0.05  [get_ports {x0_out[14]}]
set_output_delay -clock clk  0.05  [get_ports {x0_out[13]}]
set_output_delay -clock clk  0.05  [get_ports {x0_out[12]}]
set_output_delay -clock clk  0.05  [get_ports {x0_out[11]}]
set_output_delay -clock clk  0.05  [get_ports {x0_out[10]}]
set_output_delay -clock clk  0.05  [get_ports {x0_out[9]}]
set_output_delay -clock clk  0.05  [get_ports {x0_out[8]}]
set_output_delay -clock clk  0.05  [get_ports {x0_out[7]}]
set_output_delay -clock clk  0.05  [get_ports {x0_out[6]}]
set_output_delay -clock clk  0.05  [get_ports {x0_out[5]}]
set_output_delay -clock clk  0.05  [get_ports {x0_out[4]}]
set_output_delay -clock clk  0.05  [get_ports {x0_out[3]}]
set_output_delay -clock clk  0.05  [get_ports {x0_out[2]}]
set_output_delay -clock clk  0.05  [get_ports {x0_out[1]}]
set_output_delay -clock clk  0.05  [get_ports {x0_out[0]}]
set_output_delay -clock clk  0.05  [get_ports {x1_out[15]}]
set_output_delay -clock clk  0.05  [get_ports {x1_out[14]}]
set_output_delay -clock clk  0.05  [get_ports {x1_out[13]}]
set_output_delay -clock clk  0.05  [get_ports {x1_out[12]}]
set_output_delay -clock clk  0.05  [get_ports {x1_out[11]}]
set_output_delay -clock clk  0.05  [get_ports {x1_out[10]}]
set_output_delay -clock clk  0.05  [get_ports {x1_out[9]}]
set_output_delay -clock clk  0.05  [get_ports {x1_out[8]}]
set_output_delay -clock clk  0.05  [get_ports {x1_out[7]}]
set_output_delay -clock clk  0.05  [get_ports {x1_out[6]}]
set_output_delay -clock clk  0.05  [get_ports {x1_out[5]}]
set_output_delay -clock clk  0.05  [get_ports {x1_out[4]}]
set_output_delay -clock clk  0.05  [get_ports {x1_out[3]}]
set_output_delay -clock clk  0.05  [get_ports {x1_out[2]}]
set_output_delay -clock clk  0.05  [get_ports {x1_out[1]}]
set_output_delay -clock clk  0.05  [get_ports {x1_out[0]}]
set_output_delay -clock clk  0.05  [get_ports done]
