###################################################################

# Created by write_sdc on Sat Mar 14 02:58:03 2026

###################################################################
set sdc_version 1.7

set_units -time ns -resistance kOhm -capacitance pF -voltage V -current mA
set_max_fanout 4 [current_design]
set_driving_cell -lib_cell INVD0 [get_ports clk]
set_driving_cell -lib_cell INVD0 [get_ports wen]
set_driving_cell -lib_cell INVD0 [get_ports rstn]
set_driving_cell -lib_cell INVD0 [get_ports {seed[15]}]
set_driving_cell -lib_cell INVD0 [get_ports {seed[14]}]
set_driving_cell -lib_cell INVD0 [get_ports {seed[13]}]
set_driving_cell -lib_cell INVD0 [get_ports {seed[12]}]
set_driving_cell -lib_cell INVD0 [get_ports {seed[11]}]
set_driving_cell -lib_cell INVD0 [get_ports {seed[10]}]
set_driving_cell -lib_cell INVD0 [get_ports {seed[9]}]
set_driving_cell -lib_cell INVD0 [get_ports {seed[8]}]
set_driving_cell -lib_cell INVD0 [get_ports {seed[7]}]
set_driving_cell -lib_cell INVD0 [get_ports {seed[6]}]
set_driving_cell -lib_cell INVD0 [get_ports {seed[5]}]
set_driving_cell -lib_cell INVD0 [get_ports {seed[4]}]
set_driving_cell -lib_cell INVD0 [get_ports {seed[3]}]
set_driving_cell -lib_cell INVD0 [get_ports {seed[2]}]
set_driving_cell -lib_cell INVD0 [get_ports {seed[1]}]
set_driving_cell -lib_cell INVD0 [get_ports {seed[0]}]
set_load -pin_load 0.005 [get_ports {sign[15]}]
set_load -pin_load 0.005 [get_ports {sign[14]}]
set_load -pin_load 0.005 [get_ports {sign[13]}]
set_load -pin_load 0.005 [get_ports {sign[12]}]
set_load -pin_load 0.005 [get_ports {sign[11]}]
set_load -pin_load 0.005 [get_ports {sign[10]}]
set_load -pin_load 0.005 [get_ports {sign[9]}]
set_load -pin_load 0.005 [get_ports {sign[8]}]
set_load -pin_load 0.005 [get_ports {sign[7]}]
set_load -pin_load 0.005 [get_ports {sign[6]}]
set_load -pin_load 0.005 [get_ports {sign[5]}]
set_load -pin_load 0.005 [get_ports {sign[4]}]
set_load -pin_load 0.005 [get_ports {sign[3]}]
set_load -pin_load 0.005 [get_ports {sign[2]}]
set_load -pin_load 0.005 [get_ports {sign[1]}]
set_load -pin_load 0.005 [get_ports {sign[0]}]
set_max_capacitance 0.005 [get_ports clk]
set_max_capacitance 0.005 [get_ports wen]
set_max_capacitance 0.005 [get_ports rstn]
set_max_capacitance 0.005 [get_ports {seed[15]}]
set_max_capacitance 0.005 [get_ports {seed[14]}]
set_max_capacitance 0.005 [get_ports {seed[13]}]
set_max_capacitance 0.005 [get_ports {seed[12]}]
set_max_capacitance 0.005 [get_ports {seed[11]}]
set_max_capacitance 0.005 [get_ports {seed[10]}]
set_max_capacitance 0.005 [get_ports {seed[9]}]
set_max_capacitance 0.005 [get_ports {seed[8]}]
set_max_capacitance 0.005 [get_ports {seed[7]}]
set_max_capacitance 0.005 [get_ports {seed[6]}]
set_max_capacitance 0.005 [get_ports {seed[5]}]
set_max_capacitance 0.005 [get_ports {seed[4]}]
set_max_capacitance 0.005 [get_ports {seed[3]}]
set_max_capacitance 0.005 [get_ports {seed[2]}]
set_max_capacitance 0.005 [get_ports {seed[1]}]
set_max_capacitance 0.005 [get_ports {seed[0]}]
set_max_fanout 4 [get_ports clk]
set_max_fanout 4 [get_ports wen]
set_max_fanout 4 [get_ports rstn]
set_max_fanout 4 [get_ports {seed[15]}]
set_max_fanout 4 [get_ports {seed[14]}]
set_max_fanout 4 [get_ports {seed[13]}]
set_max_fanout 4 [get_ports {seed[12]}]
set_max_fanout 4 [get_ports {seed[11]}]
set_max_fanout 4 [get_ports {seed[10]}]
set_max_fanout 4 [get_ports {seed[9]}]
set_max_fanout 4 [get_ports {seed[8]}]
set_max_fanout 4 [get_ports {seed[7]}]
set_max_fanout 4 [get_ports {seed[6]}]
set_max_fanout 4 [get_ports {seed[5]}]
set_max_fanout 4 [get_ports {seed[4]}]
set_max_fanout 4 [get_ports {seed[3]}]
set_max_fanout 4 [get_ports {seed[2]}]
set_max_fanout 4 [get_ports {seed[1]}]
set_max_fanout 4 [get_ports {seed[0]}]
set_ideal_network [get_ports clk]
create_clock [get_ports clk]  -period 2  -waveform {0 1}
set_clock_uncertainty 0  [get_clocks clk]
set_clock_transition -max -rise 0.04 [get_clocks clk]
set_clock_transition -max -fall 0.04 [get_clocks clk]
set_clock_transition -min -rise 0.04 [get_clocks clk]
set_clock_transition -min -fall 0.04 [get_clocks clk]
set_input_delay -clock clk  0.05  [get_ports wen]
set_input_delay -clock clk  0.05  [get_ports rstn]
set_input_delay -clock clk  0.05  [get_ports {seed[15]}]
set_input_delay -clock clk  0.05  [get_ports {seed[14]}]
set_input_delay -clock clk  0.05  [get_ports {seed[13]}]
set_input_delay -clock clk  0.05  [get_ports {seed[12]}]
set_input_delay -clock clk  0.05  [get_ports {seed[11]}]
set_input_delay -clock clk  0.05  [get_ports {seed[10]}]
set_input_delay -clock clk  0.05  [get_ports {seed[9]}]
set_input_delay -clock clk  0.05  [get_ports {seed[8]}]
set_input_delay -clock clk  0.05  [get_ports {seed[7]}]
set_input_delay -clock clk  0.05  [get_ports {seed[6]}]
set_input_delay -clock clk  0.05  [get_ports {seed[5]}]
set_input_delay -clock clk  0.05  [get_ports {seed[4]}]
set_input_delay -clock clk  0.05  [get_ports {seed[3]}]
set_input_delay -clock clk  0.05  [get_ports {seed[2]}]
set_input_delay -clock clk  0.05  [get_ports {seed[1]}]
set_input_delay -clock clk  0.05  [get_ports {seed[0]}]
set_output_delay -clock clk  0.05  [get_ports {sign[15]}]
set_output_delay -clock clk  0.05  [get_ports {sign[14]}]
set_output_delay -clock clk  0.05  [get_ports {sign[13]}]
set_output_delay -clock clk  0.05  [get_ports {sign[12]}]
set_output_delay -clock clk  0.05  [get_ports {sign[11]}]
set_output_delay -clock clk  0.05  [get_ports {sign[10]}]
set_output_delay -clock clk  0.05  [get_ports {sign[9]}]
set_output_delay -clock clk  0.05  [get_ports {sign[8]}]
set_output_delay -clock clk  0.05  [get_ports {sign[7]}]
set_output_delay -clock clk  0.05  [get_ports {sign[6]}]
set_output_delay -clock clk  0.05  [get_ports {sign[5]}]
set_output_delay -clock clk  0.05  [get_ports {sign[4]}]
set_output_delay -clock clk  0.05  [get_ports {sign[3]}]
set_output_delay -clock clk  0.05  [get_ports {sign[2]}]
set_output_delay -clock clk  0.05  [get_ports {sign[1]}]
set_output_delay -clock clk  0.05  [get_ports {sign[0]}]
