###################################################################

# Created by write_sdc on Sat Jun 27 22:09:12 2026

###################################################################
set sdc_version 1.7

set_units -time ns -resistance kOhm -capacitance pF -voltage V -current mA
set_wire_load_mode top
set_wire_load_model -name ZeroWireload -library tcbn65gplustc_ccs
set_max_fanout 4 [current_design]
set_driving_cell -lib_cell INVD0 [get_ports clk]
set_driving_cell -lib_cell INVD0 [get_ports rstn]
set_driving_cell -lib_cell INVD0 [get_ports start]
set_driving_cell -lib_cell INVD0 [get_ports tb_data_cen]
set_driving_cell -lib_cell INVD0 [get_ports tb_data_wen]
set_driving_cell -lib_cell INVD0 [get_ports {tb_data_addr[6]}]
set_driving_cell -lib_cell INVD0 [get_ports {tb_data_addr[5]}]
set_driving_cell -lib_cell INVD0 [get_ports {tb_data_addr[4]}]
set_driving_cell -lib_cell INVD0 [get_ports {tb_data_addr[3]}]
set_driving_cell -lib_cell INVD0 [get_ports {tb_data_addr[2]}]
set_driving_cell -lib_cell INVD0 [get_ports {tb_data_addr[1]}]
set_driving_cell -lib_cell INVD0 [get_ports {tb_data_addr[0]}]
set_driving_cell -lib_cell INVD0 [get_ports {tb_data_din[15]}]
set_driving_cell -lib_cell INVD0 [get_ports {tb_data_din[14]}]
set_driving_cell -lib_cell INVD0 [get_ports {tb_data_din[13]}]
set_driving_cell -lib_cell INVD0 [get_ports {tb_data_din[12]}]
set_driving_cell -lib_cell INVD0 [get_ports {tb_data_din[11]}]
set_driving_cell -lib_cell INVD0 [get_ports {tb_data_din[10]}]
set_driving_cell -lib_cell INVD0 [get_ports {tb_data_din[9]}]
set_driving_cell -lib_cell INVD0 [get_ports {tb_data_din[8]}]
set_driving_cell -lib_cell INVD0 [get_ports {tb_data_din[7]}]
set_driving_cell -lib_cell INVD0 [get_ports {tb_data_din[6]}]
set_driving_cell -lib_cell INVD0 [get_ports {tb_data_din[5]}]
set_driving_cell -lib_cell INVD0 [get_ports {tb_data_din[4]}]
set_driving_cell -lib_cell INVD0 [get_ports {tb_data_din[3]}]
set_driving_cell -lib_cell INVD0 [get_ports {tb_data_din[2]}]
set_driving_cell -lib_cell INVD0 [get_ports {tb_data_din[1]}]
set_driving_cell -lib_cell INVD0 [get_ports {tb_data_din[0]}]
set_driving_cell -lib_cell INVD0 [get_ports tb_tw_cen]
set_driving_cell -lib_cell INVD0 [get_ports tb_tw_wen]
set_driving_cell -lib_cell INVD0 [get_ports {tb_tw_addr[5]}]
set_driving_cell -lib_cell INVD0 [get_ports {tb_tw_addr[4]}]
set_driving_cell -lib_cell INVD0 [get_ports {tb_tw_addr[3]}]
set_driving_cell -lib_cell INVD0 [get_ports {tb_tw_addr[2]}]
set_driving_cell -lib_cell INVD0 [get_ports {tb_tw_addr[1]}]
set_driving_cell -lib_cell INVD0 [get_ports {tb_tw_addr[0]}]
set_driving_cell -lib_cell INVD0 [get_ports {tb_tw_din[15]}]
set_driving_cell -lib_cell INVD0 [get_ports {tb_tw_din[14]}]
set_driving_cell -lib_cell INVD0 [get_ports {tb_tw_din[13]}]
set_driving_cell -lib_cell INVD0 [get_ports {tb_tw_din[12]}]
set_driving_cell -lib_cell INVD0 [get_ports {tb_tw_din[11]}]
set_driving_cell -lib_cell INVD0 [get_ports {tb_tw_din[10]}]
set_driving_cell -lib_cell INVD0 [get_ports {tb_tw_din[9]}]
set_driving_cell -lib_cell INVD0 [get_ports {tb_tw_din[8]}]
set_driving_cell -lib_cell INVD0 [get_ports {tb_tw_din[7]}]
set_driving_cell -lib_cell INVD0 [get_ports {tb_tw_din[6]}]
set_driving_cell -lib_cell INVD0 [get_ports {tb_tw_din[5]}]
set_driving_cell -lib_cell INVD0 [get_ports {tb_tw_din[4]}]
set_driving_cell -lib_cell INVD0 [get_ports {tb_tw_din[3]}]
set_driving_cell -lib_cell INVD0 [get_ports {tb_tw_din[2]}]
set_driving_cell -lib_cell INVD0 [get_ports {tb_tw_din[1]}]
set_driving_cell -lib_cell INVD0 [get_ports {tb_tw_din[0]}]
set_driving_cell -lib_cell INVD0 [get_ports {tb_linear_addr[6]}]
set_driving_cell -lib_cell INVD0 [get_ports {tb_linear_addr[5]}]
set_driving_cell -lib_cell INVD0 [get_ports {tb_linear_addr[4]}]
set_driving_cell -lib_cell INVD0 [get_ports {tb_linear_addr[3]}]
set_driving_cell -lib_cell INVD0 [get_ports {tb_linear_addr[2]}]
set_driving_cell -lib_cell INVD0 [get_ports {tb_linear_addr[1]}]
set_driving_cell -lib_cell INVD0 [get_ports {tb_linear_addr[0]}]
set_load -pin_load 0.005 [get_ports busy]
set_load -pin_load 0.005 [get_ports done]
set_load -pin_load 0.005 [get_ports {tb_data_dout[15]}]
set_load -pin_load 0.005 [get_ports {tb_data_dout[14]}]
set_load -pin_load 0.005 [get_ports {tb_data_dout[13]}]
set_load -pin_load 0.005 [get_ports {tb_data_dout[12]}]
set_load -pin_load 0.005 [get_ports {tb_data_dout[11]}]
set_load -pin_load 0.005 [get_ports {tb_data_dout[10]}]
set_load -pin_load 0.005 [get_ports {tb_data_dout[9]}]
set_load -pin_load 0.005 [get_ports {tb_data_dout[8]}]
set_load -pin_load 0.005 [get_ports {tb_data_dout[7]}]
set_load -pin_load 0.005 [get_ports {tb_data_dout[6]}]
set_load -pin_load 0.005 [get_ports {tb_data_dout[5]}]
set_load -pin_load 0.005 [get_ports {tb_data_dout[4]}]
set_load -pin_load 0.005 [get_ports {tb_data_dout[3]}]
set_load -pin_load 0.005 [get_ports {tb_data_dout[2]}]
set_load -pin_load 0.005 [get_ports {tb_data_dout[1]}]
set_load -pin_load 0.005 [get_ports {tb_data_dout[0]}]
set_load -pin_load 0.005 [get_ports {tb_tw_dout[15]}]
set_load -pin_load 0.005 [get_ports {tb_tw_dout[14]}]
set_load -pin_load 0.005 [get_ports {tb_tw_dout[13]}]
set_load -pin_load 0.005 [get_ports {tb_tw_dout[12]}]
set_load -pin_load 0.005 [get_ports {tb_tw_dout[11]}]
set_load -pin_load 0.005 [get_ports {tb_tw_dout[10]}]
set_load -pin_load 0.005 [get_ports {tb_tw_dout[9]}]
set_load -pin_load 0.005 [get_ports {tb_tw_dout[8]}]
set_load -pin_load 0.005 [get_ports {tb_tw_dout[7]}]
set_load -pin_load 0.005 [get_ports {tb_tw_dout[6]}]
set_load -pin_load 0.005 [get_ports {tb_tw_dout[5]}]
set_load -pin_load 0.005 [get_ports {tb_tw_dout[4]}]
set_load -pin_load 0.005 [get_ports {tb_tw_dout[3]}]
set_load -pin_load 0.005 [get_ports {tb_tw_dout[2]}]
set_load -pin_load 0.005 [get_ports {tb_tw_dout[1]}]
set_load -pin_load 0.005 [get_ports {tb_tw_dout[0]}]
set_load -pin_load 0.005 [get_ports {tb_bitrev_addr[6]}]
set_load -pin_load 0.005 [get_ports {tb_bitrev_addr[5]}]
set_load -pin_load 0.005 [get_ports {tb_bitrev_addr[4]}]
set_load -pin_load 0.005 [get_ports {tb_bitrev_addr[3]}]
set_load -pin_load 0.005 [get_ports {tb_bitrev_addr[2]}]
set_load -pin_load 0.005 [get_ports {tb_bitrev_addr[1]}]
set_load -pin_load 0.005 [get_ports {tb_bitrev_addr[0]}]
set_max_capacitance 0.01 [get_ports clk]
set_max_capacitance 0.01 [get_ports rstn]
set_max_capacitance 0.01 [get_ports start]
set_max_capacitance 0.01 [get_ports tb_data_cen]
set_max_capacitance 0.01 [get_ports tb_data_wen]
set_max_capacitance 0.01 [get_ports {tb_data_addr[6]}]
set_max_capacitance 0.01 [get_ports {tb_data_addr[5]}]
set_max_capacitance 0.01 [get_ports {tb_data_addr[4]}]
set_max_capacitance 0.01 [get_ports {tb_data_addr[3]}]
set_max_capacitance 0.01 [get_ports {tb_data_addr[2]}]
set_max_capacitance 0.01 [get_ports {tb_data_addr[1]}]
set_max_capacitance 0.01 [get_ports {tb_data_addr[0]}]
set_max_capacitance 0.01 [get_ports {tb_data_din[15]}]
set_max_capacitance 0.01 [get_ports {tb_data_din[14]}]
set_max_capacitance 0.01 [get_ports {tb_data_din[13]}]
set_max_capacitance 0.01 [get_ports {tb_data_din[12]}]
set_max_capacitance 0.01 [get_ports {tb_data_din[11]}]
set_max_capacitance 0.01 [get_ports {tb_data_din[10]}]
set_max_capacitance 0.01 [get_ports {tb_data_din[9]}]
set_max_capacitance 0.01 [get_ports {tb_data_din[8]}]
set_max_capacitance 0.01 [get_ports {tb_data_din[7]}]
set_max_capacitance 0.01 [get_ports {tb_data_din[6]}]
set_max_capacitance 0.01 [get_ports {tb_data_din[5]}]
set_max_capacitance 0.01 [get_ports {tb_data_din[4]}]
set_max_capacitance 0.01 [get_ports {tb_data_din[3]}]
set_max_capacitance 0.01 [get_ports {tb_data_din[2]}]
set_max_capacitance 0.01 [get_ports {tb_data_din[1]}]
set_max_capacitance 0.01 [get_ports {tb_data_din[0]}]
set_max_capacitance 0.01 [get_ports tb_tw_cen]
set_max_capacitance 0.01 [get_ports tb_tw_wen]
set_max_capacitance 0.01 [get_ports {tb_tw_addr[5]}]
set_max_capacitance 0.01 [get_ports {tb_tw_addr[4]}]
set_max_capacitance 0.01 [get_ports {tb_tw_addr[3]}]
set_max_capacitance 0.01 [get_ports {tb_tw_addr[2]}]
set_max_capacitance 0.01 [get_ports {tb_tw_addr[1]}]
set_max_capacitance 0.01 [get_ports {tb_tw_addr[0]}]
set_max_capacitance 0.01 [get_ports {tb_tw_din[15]}]
set_max_capacitance 0.01 [get_ports {tb_tw_din[14]}]
set_max_capacitance 0.01 [get_ports {tb_tw_din[13]}]
set_max_capacitance 0.01 [get_ports {tb_tw_din[12]}]
set_max_capacitance 0.01 [get_ports {tb_tw_din[11]}]
set_max_capacitance 0.01 [get_ports {tb_tw_din[10]}]
set_max_capacitance 0.01 [get_ports {tb_tw_din[9]}]
set_max_capacitance 0.01 [get_ports {tb_tw_din[8]}]
set_max_capacitance 0.01 [get_ports {tb_tw_din[7]}]
set_max_capacitance 0.01 [get_ports {tb_tw_din[6]}]
set_max_capacitance 0.01 [get_ports {tb_tw_din[5]}]
set_max_capacitance 0.01 [get_ports {tb_tw_din[4]}]
set_max_capacitance 0.01 [get_ports {tb_tw_din[3]}]
set_max_capacitance 0.01 [get_ports {tb_tw_din[2]}]
set_max_capacitance 0.01 [get_ports {tb_tw_din[1]}]
set_max_capacitance 0.01 [get_ports {tb_tw_din[0]}]
set_max_capacitance 0.01 [get_ports {tb_linear_addr[6]}]
set_max_capacitance 0.01 [get_ports {tb_linear_addr[5]}]
set_max_capacitance 0.01 [get_ports {tb_linear_addr[4]}]
set_max_capacitance 0.01 [get_ports {tb_linear_addr[3]}]
set_max_capacitance 0.01 [get_ports {tb_linear_addr[2]}]
set_max_capacitance 0.01 [get_ports {tb_linear_addr[1]}]
set_max_capacitance 0.01 [get_ports {tb_linear_addr[0]}]
set_max_fanout 4 [get_ports clk]
set_max_fanout 4 [get_ports rstn]
set_max_fanout 4 [get_ports start]
set_max_fanout 4 [get_ports tb_data_cen]
set_max_fanout 4 [get_ports tb_data_wen]
set_max_fanout 4 [get_ports {tb_data_addr[6]}]
set_max_fanout 4 [get_ports {tb_data_addr[5]}]
set_max_fanout 4 [get_ports {tb_data_addr[4]}]
set_max_fanout 4 [get_ports {tb_data_addr[3]}]
set_max_fanout 4 [get_ports {tb_data_addr[2]}]
set_max_fanout 4 [get_ports {tb_data_addr[1]}]
set_max_fanout 4 [get_ports {tb_data_addr[0]}]
set_max_fanout 4 [get_ports {tb_data_din[15]}]
set_max_fanout 4 [get_ports {tb_data_din[14]}]
set_max_fanout 4 [get_ports {tb_data_din[13]}]
set_max_fanout 4 [get_ports {tb_data_din[12]}]
set_max_fanout 4 [get_ports {tb_data_din[11]}]
set_max_fanout 4 [get_ports {tb_data_din[10]}]
set_max_fanout 4 [get_ports {tb_data_din[9]}]
set_max_fanout 4 [get_ports {tb_data_din[8]}]
set_max_fanout 4 [get_ports {tb_data_din[7]}]
set_max_fanout 4 [get_ports {tb_data_din[6]}]
set_max_fanout 4 [get_ports {tb_data_din[5]}]
set_max_fanout 4 [get_ports {tb_data_din[4]}]
set_max_fanout 4 [get_ports {tb_data_din[3]}]
set_max_fanout 4 [get_ports {tb_data_din[2]}]
set_max_fanout 4 [get_ports {tb_data_din[1]}]
set_max_fanout 4 [get_ports {tb_data_din[0]}]
set_max_fanout 4 [get_ports tb_tw_cen]
set_max_fanout 4 [get_ports tb_tw_wen]
set_max_fanout 4 [get_ports {tb_tw_addr[5]}]
set_max_fanout 4 [get_ports {tb_tw_addr[4]}]
set_max_fanout 4 [get_ports {tb_tw_addr[3]}]
set_max_fanout 4 [get_ports {tb_tw_addr[2]}]
set_max_fanout 4 [get_ports {tb_tw_addr[1]}]
set_max_fanout 4 [get_ports {tb_tw_addr[0]}]
set_max_fanout 4 [get_ports {tb_tw_din[15]}]
set_max_fanout 4 [get_ports {tb_tw_din[14]}]
set_max_fanout 4 [get_ports {tb_tw_din[13]}]
set_max_fanout 4 [get_ports {tb_tw_din[12]}]
set_max_fanout 4 [get_ports {tb_tw_din[11]}]
set_max_fanout 4 [get_ports {tb_tw_din[10]}]
set_max_fanout 4 [get_ports {tb_tw_din[9]}]
set_max_fanout 4 [get_ports {tb_tw_din[8]}]
set_max_fanout 4 [get_ports {tb_tw_din[7]}]
set_max_fanout 4 [get_ports {tb_tw_din[6]}]
set_max_fanout 4 [get_ports {tb_tw_din[5]}]
set_max_fanout 4 [get_ports {tb_tw_din[4]}]
set_max_fanout 4 [get_ports {tb_tw_din[3]}]
set_max_fanout 4 [get_ports {tb_tw_din[2]}]
set_max_fanout 4 [get_ports {tb_tw_din[1]}]
set_max_fanout 4 [get_ports {tb_tw_din[0]}]
set_max_fanout 4 [get_ports {tb_linear_addr[6]}]
set_max_fanout 4 [get_ports {tb_linear_addr[5]}]
set_max_fanout 4 [get_ports {tb_linear_addr[4]}]
set_max_fanout 4 [get_ports {tb_linear_addr[3]}]
set_max_fanout 4 [get_ports {tb_linear_addr[2]}]
set_max_fanout 4 [get_ports {tb_linear_addr[1]}]
set_max_fanout 4 [get_ports {tb_linear_addr[0]}]
create_clock [get_ports clk]  -period 4  -waveform {0 2}
set_clock_uncertainty 0  [get_clocks clk]
set_clock_transition -max -rise 0.12 [get_clocks clk]
set_clock_transition -max -fall 0.12 [get_clocks clk]
set_clock_transition -min -rise 0.12 [get_clocks clk]
set_clock_transition -min -fall 0.12 [get_clocks clk]
set_input_delay -clock clk  0.5  [get_ports rstn]
set_input_delay -clock clk  0.5  [get_ports start]
set_input_delay -clock clk  0.5  [get_ports tb_data_cen]
set_input_delay -clock clk  0.5  [get_ports tb_data_wen]
set_input_delay -clock clk  0.5  [get_ports {tb_data_addr[6]}]
set_input_delay -clock clk  0.5  [get_ports {tb_data_addr[5]}]
set_input_delay -clock clk  0.5  [get_ports {tb_data_addr[4]}]
set_input_delay -clock clk  0.5  [get_ports {tb_data_addr[3]}]
set_input_delay -clock clk  0.5  [get_ports {tb_data_addr[2]}]
set_input_delay -clock clk  0.5  [get_ports {tb_data_addr[1]}]
set_input_delay -clock clk  0.5  [get_ports {tb_data_addr[0]}]
set_input_delay -clock clk  0.5  [get_ports {tb_data_din[15]}]
set_input_delay -clock clk  0.5  [get_ports {tb_data_din[14]}]
set_input_delay -clock clk  0.5  [get_ports {tb_data_din[13]}]
set_input_delay -clock clk  0.5  [get_ports {tb_data_din[12]}]
set_input_delay -clock clk  0.5  [get_ports {tb_data_din[11]}]
set_input_delay -clock clk  0.5  [get_ports {tb_data_din[10]}]
set_input_delay -clock clk  0.5  [get_ports {tb_data_din[9]}]
set_input_delay -clock clk  0.5  [get_ports {tb_data_din[8]}]
set_input_delay -clock clk  0.5  [get_ports {tb_data_din[7]}]
set_input_delay -clock clk  0.5  [get_ports {tb_data_din[6]}]
set_input_delay -clock clk  0.5  [get_ports {tb_data_din[5]}]
set_input_delay -clock clk  0.5  [get_ports {tb_data_din[4]}]
set_input_delay -clock clk  0.5  [get_ports {tb_data_din[3]}]
set_input_delay -clock clk  0.5  [get_ports {tb_data_din[2]}]
set_input_delay -clock clk  0.5  [get_ports {tb_data_din[1]}]
set_input_delay -clock clk  0.5  [get_ports {tb_data_din[0]}]
set_input_delay -clock clk  0.5  [get_ports tb_tw_cen]
set_input_delay -clock clk  0.5  [get_ports tb_tw_wen]
set_input_delay -clock clk  0.5  [get_ports {tb_tw_addr[5]}]
set_input_delay -clock clk  0.5  [get_ports {tb_tw_addr[4]}]
set_input_delay -clock clk  0.5  [get_ports {tb_tw_addr[3]}]
set_input_delay -clock clk  0.5  [get_ports {tb_tw_addr[2]}]
set_input_delay -clock clk  0.5  [get_ports {tb_tw_addr[1]}]
set_input_delay -clock clk  0.5  [get_ports {tb_tw_addr[0]}]
set_input_delay -clock clk  0.5  [get_ports {tb_tw_din[15]}]
set_input_delay -clock clk  0.5  [get_ports {tb_tw_din[14]}]
set_input_delay -clock clk  0.5  [get_ports {tb_tw_din[13]}]
set_input_delay -clock clk  0.5  [get_ports {tb_tw_din[12]}]
set_input_delay -clock clk  0.5  [get_ports {tb_tw_din[11]}]
set_input_delay -clock clk  0.5  [get_ports {tb_tw_din[10]}]
set_input_delay -clock clk  0.5  [get_ports {tb_tw_din[9]}]
set_input_delay -clock clk  0.5  [get_ports {tb_tw_din[8]}]
set_input_delay -clock clk  0.5  [get_ports {tb_tw_din[7]}]
set_input_delay -clock clk  0.5  [get_ports {tb_tw_din[6]}]
set_input_delay -clock clk  0.5  [get_ports {tb_tw_din[5]}]
set_input_delay -clock clk  0.5  [get_ports {tb_tw_din[4]}]
set_input_delay -clock clk  0.5  [get_ports {tb_tw_din[3]}]
set_input_delay -clock clk  0.5  [get_ports {tb_tw_din[2]}]
set_input_delay -clock clk  0.5  [get_ports {tb_tw_din[1]}]
set_input_delay -clock clk  0.5  [get_ports {tb_tw_din[0]}]
set_input_delay -clock clk  0.5  [get_ports {tb_linear_addr[6]}]
set_input_delay -clock clk  0.5  [get_ports {tb_linear_addr[5]}]
set_input_delay -clock clk  0.5  [get_ports {tb_linear_addr[4]}]
set_input_delay -clock clk  0.5  [get_ports {tb_linear_addr[3]}]
set_input_delay -clock clk  0.5  [get_ports {tb_linear_addr[2]}]
set_input_delay -clock clk  0.5  [get_ports {tb_linear_addr[1]}]
set_input_delay -clock clk  0.5  [get_ports {tb_linear_addr[0]}]
set_output_delay -clock clk  0.1  [get_ports busy]
set_output_delay -clock clk  0.1  [get_ports done]
set_output_delay -clock clk  0.1  [get_ports {tb_data_dout[15]}]
set_output_delay -clock clk  0.1  [get_ports {tb_data_dout[14]}]
set_output_delay -clock clk  0.1  [get_ports {tb_data_dout[13]}]
set_output_delay -clock clk  0.1  [get_ports {tb_data_dout[12]}]
set_output_delay -clock clk  0.1  [get_ports {tb_data_dout[11]}]
set_output_delay -clock clk  0.1  [get_ports {tb_data_dout[10]}]
set_output_delay -clock clk  0.1  [get_ports {tb_data_dout[9]}]
set_output_delay -clock clk  0.1  [get_ports {tb_data_dout[8]}]
set_output_delay -clock clk  0.1  [get_ports {tb_data_dout[7]}]
set_output_delay -clock clk  0.1  [get_ports {tb_data_dout[6]}]
set_output_delay -clock clk  0.1  [get_ports {tb_data_dout[5]}]
set_output_delay -clock clk  0.1  [get_ports {tb_data_dout[4]}]
set_output_delay -clock clk  0.1  [get_ports {tb_data_dout[3]}]
set_output_delay -clock clk  0.1  [get_ports {tb_data_dout[2]}]
set_output_delay -clock clk  0.1  [get_ports {tb_data_dout[1]}]
set_output_delay -clock clk  0.1  [get_ports {tb_data_dout[0]}]
set_output_delay -clock clk  0.1  [get_ports {tb_tw_dout[15]}]
set_output_delay -clock clk  0.1  [get_ports {tb_tw_dout[14]}]
set_output_delay -clock clk  0.1  [get_ports {tb_tw_dout[13]}]
set_output_delay -clock clk  0.1  [get_ports {tb_tw_dout[12]}]
set_output_delay -clock clk  0.1  [get_ports {tb_tw_dout[11]}]
set_output_delay -clock clk  0.1  [get_ports {tb_tw_dout[10]}]
set_output_delay -clock clk  0.1  [get_ports {tb_tw_dout[9]}]
set_output_delay -clock clk  0.1  [get_ports {tb_tw_dout[8]}]
set_output_delay -clock clk  0.1  [get_ports {tb_tw_dout[7]}]
set_output_delay -clock clk  0.1  [get_ports {tb_tw_dout[6]}]
set_output_delay -clock clk  0.1  [get_ports {tb_tw_dout[5]}]
set_output_delay -clock clk  0.1  [get_ports {tb_tw_dout[4]}]
set_output_delay -clock clk  0.1  [get_ports {tb_tw_dout[3]}]
set_output_delay -clock clk  0.1  [get_ports {tb_tw_dout[2]}]
set_output_delay -clock clk  0.1  [get_ports {tb_tw_dout[1]}]
set_output_delay -clock clk  0.1  [get_ports {tb_tw_dout[0]}]
set_output_delay -clock clk  0.1  [get_ports {tb_bitrev_addr[6]}]
set_output_delay -clock clk  0.1  [get_ports {tb_bitrev_addr[5]}]
set_output_delay -clock clk  0.1  [get_ports {tb_bitrev_addr[4]}]
set_output_delay -clock clk  0.1  [get_ports {tb_bitrev_addr[3]}]
set_output_delay -clock clk  0.1  [get_ports {tb_bitrev_addr[2]}]
set_output_delay -clock clk  0.1  [get_ports {tb_bitrev_addr[1]}]
set_output_delay -clock clk  0.1  [get_ports {tb_bitrev_addr[0]}]
