###################################################################

# Created by write_sdc on Sat Jun 27 21:38:32 2026

###################################################################
set sdc_version 1.7

set_units -time ns -resistance kOhm -capacitance pF -voltage V -current mA
set_wire_load_mode top
set_wire_load_model -name ZeroWireload -library tcbn65gplustc_ccs
set_max_fanout 4 [current_design]
set_driving_cell -lib_cell INVD0 [get_ports clk]
set_driving_cell -lib_cell INVD0 [get_ports rstn]
set_driving_cell -lib_cell INVD0 [get_ports start]
set_driving_cell -lib_cell INVD0 [get_ports {data_dout[15]}]
set_driving_cell -lib_cell INVD0 [get_ports {data_dout[14]}]
set_driving_cell -lib_cell INVD0 [get_ports {data_dout[13]}]
set_driving_cell -lib_cell INVD0 [get_ports {data_dout[12]}]
set_driving_cell -lib_cell INVD0 [get_ports {data_dout[11]}]
set_driving_cell -lib_cell INVD0 [get_ports {data_dout[10]}]
set_driving_cell -lib_cell INVD0 [get_ports {data_dout[9]}]
set_driving_cell -lib_cell INVD0 [get_ports {data_dout[8]}]
set_driving_cell -lib_cell INVD0 [get_ports {data_dout[7]}]
set_driving_cell -lib_cell INVD0 [get_ports {data_dout[6]}]
set_driving_cell -lib_cell INVD0 [get_ports {data_dout[5]}]
set_driving_cell -lib_cell INVD0 [get_ports {data_dout[4]}]
set_driving_cell -lib_cell INVD0 [get_ports {data_dout[3]}]
set_driving_cell -lib_cell INVD0 [get_ports {data_dout[2]}]
set_driving_cell -lib_cell INVD0 [get_ports {data_dout[1]}]
set_driving_cell -lib_cell INVD0 [get_ports {data_dout[0]}]
set_driving_cell -lib_cell INVD0 [get_ports {tw_dout[15]}]
set_driving_cell -lib_cell INVD0 [get_ports {tw_dout[14]}]
set_driving_cell -lib_cell INVD0 [get_ports {tw_dout[13]}]
set_driving_cell -lib_cell INVD0 [get_ports {tw_dout[12]}]
set_driving_cell -lib_cell INVD0 [get_ports {tw_dout[11]}]
set_driving_cell -lib_cell INVD0 [get_ports {tw_dout[10]}]
set_driving_cell -lib_cell INVD0 [get_ports {tw_dout[9]}]
set_driving_cell -lib_cell INVD0 [get_ports {tw_dout[8]}]
set_driving_cell -lib_cell INVD0 [get_ports {tw_dout[7]}]
set_driving_cell -lib_cell INVD0 [get_ports {tw_dout[6]}]
set_driving_cell -lib_cell INVD0 [get_ports {tw_dout[5]}]
set_driving_cell -lib_cell INVD0 [get_ports {tw_dout[4]}]
set_driving_cell -lib_cell INVD0 [get_ports {tw_dout[3]}]
set_driving_cell -lib_cell INVD0 [get_ports {tw_dout[2]}]
set_driving_cell -lib_cell INVD0 [get_ports {tw_dout[1]}]
set_driving_cell -lib_cell INVD0 [get_ports {tw_dout[0]}]
set_driving_cell -lib_cell INVD0 [get_ports core_done]
set_driving_cell -lib_cell INVD0 [get_ports {core_x0_out[15]}]
set_driving_cell -lib_cell INVD0 [get_ports {core_x0_out[14]}]
set_driving_cell -lib_cell INVD0 [get_ports {core_x0_out[13]}]
set_driving_cell -lib_cell INVD0 [get_ports {core_x0_out[12]}]
set_driving_cell -lib_cell INVD0 [get_ports {core_x0_out[11]}]
set_driving_cell -lib_cell INVD0 [get_ports {core_x0_out[10]}]
set_driving_cell -lib_cell INVD0 [get_ports {core_x0_out[9]}]
set_driving_cell -lib_cell INVD0 [get_ports {core_x0_out[8]}]
set_driving_cell -lib_cell INVD0 [get_ports {core_x0_out[7]}]
set_driving_cell -lib_cell INVD0 [get_ports {core_x0_out[6]}]
set_driving_cell -lib_cell INVD0 [get_ports {core_x0_out[5]}]
set_driving_cell -lib_cell INVD0 [get_ports {core_x0_out[4]}]
set_driving_cell -lib_cell INVD0 [get_ports {core_x0_out[3]}]
set_driving_cell -lib_cell INVD0 [get_ports {core_x0_out[2]}]
set_driving_cell -lib_cell INVD0 [get_ports {core_x0_out[1]}]
set_driving_cell -lib_cell INVD0 [get_ports {core_x0_out[0]}]
set_driving_cell -lib_cell INVD0 [get_ports {core_x1_out[15]}]
set_driving_cell -lib_cell INVD0 [get_ports {core_x1_out[14]}]
set_driving_cell -lib_cell INVD0 [get_ports {core_x1_out[13]}]
set_driving_cell -lib_cell INVD0 [get_ports {core_x1_out[12]}]
set_driving_cell -lib_cell INVD0 [get_ports {core_x1_out[11]}]
set_driving_cell -lib_cell INVD0 [get_ports {core_x1_out[10]}]
set_driving_cell -lib_cell INVD0 [get_ports {core_x1_out[9]}]
set_driving_cell -lib_cell INVD0 [get_ports {core_x1_out[8]}]
set_driving_cell -lib_cell INVD0 [get_ports {core_x1_out[7]}]
set_driving_cell -lib_cell INVD0 [get_ports {core_x1_out[6]}]
set_driving_cell -lib_cell INVD0 [get_ports {core_x1_out[5]}]
set_driving_cell -lib_cell INVD0 [get_ports {core_x1_out[4]}]
set_driving_cell -lib_cell INVD0 [get_ports {core_x1_out[3]}]
set_driving_cell -lib_cell INVD0 [get_ports {core_x1_out[2]}]
set_driving_cell -lib_cell INVD0 [get_ports {core_x1_out[1]}]
set_driving_cell -lib_cell INVD0 [get_ports {core_x1_out[0]}]
set_driving_cell -lib_cell INVD0 [get_ports {x0_addr[6]}]
set_driving_cell -lib_cell INVD0 [get_ports {x0_addr[5]}]
set_driving_cell -lib_cell INVD0 [get_ports {x0_addr[4]}]
set_driving_cell -lib_cell INVD0 [get_ports {x0_addr[3]}]
set_driving_cell -lib_cell INVD0 [get_ports {x0_addr[2]}]
set_driving_cell -lib_cell INVD0 [get_ports {x0_addr[1]}]
set_driving_cell -lib_cell INVD0 [get_ports {x0_addr[0]}]
set_driving_cell -lib_cell INVD0 [get_ports {x1_addr[6]}]
set_driving_cell -lib_cell INVD0 [get_ports {x1_addr[5]}]
set_driving_cell -lib_cell INVD0 [get_ports {x1_addr[4]}]
set_driving_cell -lib_cell INVD0 [get_ports {x1_addr[3]}]
set_driving_cell -lib_cell INVD0 [get_ports {x1_addr[2]}]
set_driving_cell -lib_cell INVD0 [get_ports {x1_addr[1]}]
set_driving_cell -lib_cell INVD0 [get_ports {x1_addr[0]}]
set_driving_cell -lib_cell INVD0 [get_ports {w_addr[5]}]
set_driving_cell -lib_cell INVD0 [get_ports {w_addr[4]}]
set_driving_cell -lib_cell INVD0 [get_ports {w_addr[3]}]
set_driving_cell -lib_cell INVD0 [get_ports {w_addr[2]}]
set_driving_cell -lib_cell INVD0 [get_ports {w_addr[1]}]
set_driving_cell -lib_cell INVD0 [get_ports {w_addr[0]}]
set_load -pin_load 0.005 [get_ports core_start]
set_load -pin_load 0.005 [get_ports {core_x0[15]}]
set_load -pin_load 0.005 [get_ports {core_x0[14]}]
set_load -pin_load 0.005 [get_ports {core_x0[13]}]
set_load -pin_load 0.005 [get_ports {core_x0[12]}]
set_load -pin_load 0.005 [get_ports {core_x0[11]}]
set_load -pin_load 0.005 [get_ports {core_x0[10]}]
set_load -pin_load 0.005 [get_ports {core_x0[9]}]
set_load -pin_load 0.005 [get_ports {core_x0[8]}]
set_load -pin_load 0.005 [get_ports {core_x0[7]}]
set_load -pin_load 0.005 [get_ports {core_x0[6]}]
set_load -pin_load 0.005 [get_ports {core_x0[5]}]
set_load -pin_load 0.005 [get_ports {core_x0[4]}]
set_load -pin_load 0.005 [get_ports {core_x0[3]}]
set_load -pin_load 0.005 [get_ports {core_x0[2]}]
set_load -pin_load 0.005 [get_ports {core_x0[1]}]
set_load -pin_load 0.005 [get_ports {core_x0[0]}]
set_load -pin_load 0.005 [get_ports {core_x1[15]}]
set_load -pin_load 0.005 [get_ports {core_x1[14]}]
set_load -pin_load 0.005 [get_ports {core_x1[13]}]
set_load -pin_load 0.005 [get_ports {core_x1[12]}]
set_load -pin_load 0.005 [get_ports {core_x1[11]}]
set_load -pin_load 0.005 [get_ports {core_x1[10]}]
set_load -pin_load 0.005 [get_ports {core_x1[9]}]
set_load -pin_load 0.005 [get_ports {core_x1[8]}]
set_load -pin_load 0.005 [get_ports {core_x1[7]}]
set_load -pin_load 0.005 [get_ports {core_x1[6]}]
set_load -pin_load 0.005 [get_ports {core_x1[5]}]
set_load -pin_load 0.005 [get_ports {core_x1[4]}]
set_load -pin_load 0.005 [get_ports {core_x1[3]}]
set_load -pin_load 0.005 [get_ports {core_x1[2]}]
set_load -pin_load 0.005 [get_ports {core_x1[1]}]
set_load -pin_load 0.005 [get_ports {core_x1[0]}]
set_load -pin_load 0.005 [get_ports {core_w[15]}]
set_load -pin_load 0.005 [get_ports {core_w[14]}]
set_load -pin_load 0.005 [get_ports {core_w[13]}]
set_load -pin_load 0.005 [get_ports {core_w[12]}]
set_load -pin_load 0.005 [get_ports {core_w[11]}]
set_load -pin_load 0.005 [get_ports {core_w[10]}]
set_load -pin_load 0.005 [get_ports {core_w[9]}]
set_load -pin_load 0.005 [get_ports {core_w[8]}]
set_load -pin_load 0.005 [get_ports {core_w[7]}]
set_load -pin_load 0.005 [get_ports {core_w[6]}]
set_load -pin_load 0.005 [get_ports {core_w[5]}]
set_load -pin_load 0.005 [get_ports {core_w[4]}]
set_load -pin_load 0.005 [get_ports {core_w[3]}]
set_load -pin_load 0.005 [get_ports {core_w[2]}]
set_load -pin_load 0.005 [get_ports {core_w[1]}]
set_load -pin_load 0.005 [get_ports {core_w[0]}]
set_load -pin_load 0.005 [get_ports {stage[2]}]
set_load -pin_load 0.005 [get_ports {stage[1]}]
set_load -pin_load 0.005 [get_ports {stage[0]}]
set_load -pin_load 0.005 [get_ports {group[5]}]
set_load -pin_load 0.005 [get_ports {group[4]}]
set_load -pin_load 0.005 [get_ports {group[3]}]
set_load -pin_load 0.005 [get_ports {group[2]}]
set_load -pin_load 0.005 [get_ports {group[1]}]
set_load -pin_load 0.005 [get_ports {group[0]}]
set_load -pin_load 0.005 [get_ports {bfly[5]}]
set_load -pin_load 0.005 [get_ports {bfly[4]}]
set_load -pin_load 0.005 [get_ports {bfly[3]}]
set_load -pin_load 0.005 [get_ports {bfly[2]}]
set_load -pin_load 0.005 [get_ports {bfly[1]}]
set_load -pin_load 0.005 [get_ports {bfly[0]}]
set_load -pin_load 0.005 [get_ports data_cen]
set_load -pin_load 0.005 [get_ports data_wen]
set_load -pin_load 0.005 [get_ports {data_addr[6]}]
set_load -pin_load 0.005 [get_ports {data_addr[5]}]
set_load -pin_load 0.005 [get_ports {data_addr[4]}]
set_load -pin_load 0.005 [get_ports {data_addr[3]}]
set_load -pin_load 0.005 [get_ports {data_addr[2]}]
set_load -pin_load 0.005 [get_ports {data_addr[1]}]
set_load -pin_load 0.005 [get_ports {data_addr[0]}]
set_load -pin_load 0.005 [get_ports {data_din[15]}]
set_load -pin_load 0.005 [get_ports {data_din[14]}]
set_load -pin_load 0.005 [get_ports {data_din[13]}]
set_load -pin_load 0.005 [get_ports {data_din[12]}]
set_load -pin_load 0.005 [get_ports {data_din[11]}]
set_load -pin_load 0.005 [get_ports {data_din[10]}]
set_load -pin_load 0.005 [get_ports {data_din[9]}]
set_load -pin_load 0.005 [get_ports {data_din[8]}]
set_load -pin_load 0.005 [get_ports {data_din[7]}]
set_load -pin_load 0.005 [get_ports {data_din[6]}]
set_load -pin_load 0.005 [get_ports {data_din[5]}]
set_load -pin_load 0.005 [get_ports {data_din[4]}]
set_load -pin_load 0.005 [get_ports {data_din[3]}]
set_load -pin_load 0.005 [get_ports {data_din[2]}]
set_load -pin_load 0.005 [get_ports {data_din[1]}]
set_load -pin_load 0.005 [get_ports {data_din[0]}]
set_load -pin_load 0.005 [get_ports tw_cen]
set_load -pin_load 0.005 [get_ports {tw_addr[5]}]
set_load -pin_load 0.005 [get_ports {tw_addr[4]}]
set_load -pin_load 0.005 [get_ports {tw_addr[3]}]
set_load -pin_load 0.005 [get_ports {tw_addr[2]}]
set_load -pin_load 0.005 [get_ports {tw_addr[1]}]
set_load -pin_load 0.005 [get_ports {tw_addr[0]}]
set_load -pin_load 0.005 [get_ports sram_tb_sel]
set_load -pin_load 0.005 [get_ports busy]
set_load -pin_load 0.005 [get_ports done]
set_max_capacitance 0.01 [get_ports clk]
set_max_capacitance 0.01 [get_ports rstn]
set_max_capacitance 0.01 [get_ports start]
set_max_capacitance 0.01 [get_ports {data_dout[15]}]
set_max_capacitance 0.01 [get_ports {data_dout[14]}]
set_max_capacitance 0.01 [get_ports {data_dout[13]}]
set_max_capacitance 0.01 [get_ports {data_dout[12]}]
set_max_capacitance 0.01 [get_ports {data_dout[11]}]
set_max_capacitance 0.01 [get_ports {data_dout[10]}]
set_max_capacitance 0.01 [get_ports {data_dout[9]}]
set_max_capacitance 0.01 [get_ports {data_dout[8]}]
set_max_capacitance 0.01 [get_ports {data_dout[7]}]
set_max_capacitance 0.01 [get_ports {data_dout[6]}]
set_max_capacitance 0.01 [get_ports {data_dout[5]}]
set_max_capacitance 0.01 [get_ports {data_dout[4]}]
set_max_capacitance 0.01 [get_ports {data_dout[3]}]
set_max_capacitance 0.01 [get_ports {data_dout[2]}]
set_max_capacitance 0.01 [get_ports {data_dout[1]}]
set_max_capacitance 0.01 [get_ports {data_dout[0]}]
set_max_capacitance 0.01 [get_ports {tw_dout[15]}]
set_max_capacitance 0.01 [get_ports {tw_dout[14]}]
set_max_capacitance 0.01 [get_ports {tw_dout[13]}]
set_max_capacitance 0.01 [get_ports {tw_dout[12]}]
set_max_capacitance 0.01 [get_ports {tw_dout[11]}]
set_max_capacitance 0.01 [get_ports {tw_dout[10]}]
set_max_capacitance 0.01 [get_ports {tw_dout[9]}]
set_max_capacitance 0.01 [get_ports {tw_dout[8]}]
set_max_capacitance 0.01 [get_ports {tw_dout[7]}]
set_max_capacitance 0.01 [get_ports {tw_dout[6]}]
set_max_capacitance 0.01 [get_ports {tw_dout[5]}]
set_max_capacitance 0.01 [get_ports {tw_dout[4]}]
set_max_capacitance 0.01 [get_ports {tw_dout[3]}]
set_max_capacitance 0.01 [get_ports {tw_dout[2]}]
set_max_capacitance 0.01 [get_ports {tw_dout[1]}]
set_max_capacitance 0.01 [get_ports {tw_dout[0]}]
set_max_capacitance 0.01 [get_ports core_done]
set_max_capacitance 0.01 [get_ports {core_x0_out[15]}]
set_max_capacitance 0.01 [get_ports {core_x0_out[14]}]
set_max_capacitance 0.01 [get_ports {core_x0_out[13]}]
set_max_capacitance 0.01 [get_ports {core_x0_out[12]}]
set_max_capacitance 0.01 [get_ports {core_x0_out[11]}]
set_max_capacitance 0.01 [get_ports {core_x0_out[10]}]
set_max_capacitance 0.01 [get_ports {core_x0_out[9]}]
set_max_capacitance 0.01 [get_ports {core_x0_out[8]}]
set_max_capacitance 0.01 [get_ports {core_x0_out[7]}]
set_max_capacitance 0.01 [get_ports {core_x0_out[6]}]
set_max_capacitance 0.01 [get_ports {core_x0_out[5]}]
set_max_capacitance 0.01 [get_ports {core_x0_out[4]}]
set_max_capacitance 0.01 [get_ports {core_x0_out[3]}]
set_max_capacitance 0.01 [get_ports {core_x0_out[2]}]
set_max_capacitance 0.01 [get_ports {core_x0_out[1]}]
set_max_capacitance 0.01 [get_ports {core_x0_out[0]}]
set_max_capacitance 0.01 [get_ports {core_x1_out[15]}]
set_max_capacitance 0.01 [get_ports {core_x1_out[14]}]
set_max_capacitance 0.01 [get_ports {core_x1_out[13]}]
set_max_capacitance 0.01 [get_ports {core_x1_out[12]}]
set_max_capacitance 0.01 [get_ports {core_x1_out[11]}]
set_max_capacitance 0.01 [get_ports {core_x1_out[10]}]
set_max_capacitance 0.01 [get_ports {core_x1_out[9]}]
set_max_capacitance 0.01 [get_ports {core_x1_out[8]}]
set_max_capacitance 0.01 [get_ports {core_x1_out[7]}]
set_max_capacitance 0.01 [get_ports {core_x1_out[6]}]
set_max_capacitance 0.01 [get_ports {core_x1_out[5]}]
set_max_capacitance 0.01 [get_ports {core_x1_out[4]}]
set_max_capacitance 0.01 [get_ports {core_x1_out[3]}]
set_max_capacitance 0.01 [get_ports {core_x1_out[2]}]
set_max_capacitance 0.01 [get_ports {core_x1_out[1]}]
set_max_capacitance 0.01 [get_ports {core_x1_out[0]}]
set_max_capacitance 0.01 [get_ports {x0_addr[6]}]
set_max_capacitance 0.01 [get_ports {x0_addr[5]}]
set_max_capacitance 0.01 [get_ports {x0_addr[4]}]
set_max_capacitance 0.01 [get_ports {x0_addr[3]}]
set_max_capacitance 0.01 [get_ports {x0_addr[2]}]
set_max_capacitance 0.01 [get_ports {x0_addr[1]}]
set_max_capacitance 0.01 [get_ports {x0_addr[0]}]
set_max_capacitance 0.01 [get_ports {x1_addr[6]}]
set_max_capacitance 0.01 [get_ports {x1_addr[5]}]
set_max_capacitance 0.01 [get_ports {x1_addr[4]}]
set_max_capacitance 0.01 [get_ports {x1_addr[3]}]
set_max_capacitance 0.01 [get_ports {x1_addr[2]}]
set_max_capacitance 0.01 [get_ports {x1_addr[1]}]
set_max_capacitance 0.01 [get_ports {x1_addr[0]}]
set_max_capacitance 0.01 [get_ports {w_addr[5]}]
set_max_capacitance 0.01 [get_ports {w_addr[4]}]
set_max_capacitance 0.01 [get_ports {w_addr[3]}]
set_max_capacitance 0.01 [get_ports {w_addr[2]}]
set_max_capacitance 0.01 [get_ports {w_addr[1]}]
set_max_capacitance 0.01 [get_ports {w_addr[0]}]
set_max_fanout 4 [get_ports clk]
set_max_fanout 4 [get_ports rstn]
set_max_fanout 4 [get_ports start]
set_max_fanout 4 [get_ports {data_dout[15]}]
set_max_fanout 4 [get_ports {data_dout[14]}]
set_max_fanout 4 [get_ports {data_dout[13]}]
set_max_fanout 4 [get_ports {data_dout[12]}]
set_max_fanout 4 [get_ports {data_dout[11]}]
set_max_fanout 4 [get_ports {data_dout[10]}]
set_max_fanout 4 [get_ports {data_dout[9]}]
set_max_fanout 4 [get_ports {data_dout[8]}]
set_max_fanout 4 [get_ports {data_dout[7]}]
set_max_fanout 4 [get_ports {data_dout[6]}]
set_max_fanout 4 [get_ports {data_dout[5]}]
set_max_fanout 4 [get_ports {data_dout[4]}]
set_max_fanout 4 [get_ports {data_dout[3]}]
set_max_fanout 4 [get_ports {data_dout[2]}]
set_max_fanout 4 [get_ports {data_dout[1]}]
set_max_fanout 4 [get_ports {data_dout[0]}]
set_max_fanout 4 [get_ports {tw_dout[15]}]
set_max_fanout 4 [get_ports {tw_dout[14]}]
set_max_fanout 4 [get_ports {tw_dout[13]}]
set_max_fanout 4 [get_ports {tw_dout[12]}]
set_max_fanout 4 [get_ports {tw_dout[11]}]
set_max_fanout 4 [get_ports {tw_dout[10]}]
set_max_fanout 4 [get_ports {tw_dout[9]}]
set_max_fanout 4 [get_ports {tw_dout[8]}]
set_max_fanout 4 [get_ports {tw_dout[7]}]
set_max_fanout 4 [get_ports {tw_dout[6]}]
set_max_fanout 4 [get_ports {tw_dout[5]}]
set_max_fanout 4 [get_ports {tw_dout[4]}]
set_max_fanout 4 [get_ports {tw_dout[3]}]
set_max_fanout 4 [get_ports {tw_dout[2]}]
set_max_fanout 4 [get_ports {tw_dout[1]}]
set_max_fanout 4 [get_ports {tw_dout[0]}]
set_max_fanout 4 [get_ports core_done]
set_max_fanout 4 [get_ports {core_x0_out[15]}]
set_max_fanout 4 [get_ports {core_x0_out[14]}]
set_max_fanout 4 [get_ports {core_x0_out[13]}]
set_max_fanout 4 [get_ports {core_x0_out[12]}]
set_max_fanout 4 [get_ports {core_x0_out[11]}]
set_max_fanout 4 [get_ports {core_x0_out[10]}]
set_max_fanout 4 [get_ports {core_x0_out[9]}]
set_max_fanout 4 [get_ports {core_x0_out[8]}]
set_max_fanout 4 [get_ports {core_x0_out[7]}]
set_max_fanout 4 [get_ports {core_x0_out[6]}]
set_max_fanout 4 [get_ports {core_x0_out[5]}]
set_max_fanout 4 [get_ports {core_x0_out[4]}]
set_max_fanout 4 [get_ports {core_x0_out[3]}]
set_max_fanout 4 [get_ports {core_x0_out[2]}]
set_max_fanout 4 [get_ports {core_x0_out[1]}]
set_max_fanout 4 [get_ports {core_x0_out[0]}]
set_max_fanout 4 [get_ports {core_x1_out[15]}]
set_max_fanout 4 [get_ports {core_x1_out[14]}]
set_max_fanout 4 [get_ports {core_x1_out[13]}]
set_max_fanout 4 [get_ports {core_x1_out[12]}]
set_max_fanout 4 [get_ports {core_x1_out[11]}]
set_max_fanout 4 [get_ports {core_x1_out[10]}]
set_max_fanout 4 [get_ports {core_x1_out[9]}]
set_max_fanout 4 [get_ports {core_x1_out[8]}]
set_max_fanout 4 [get_ports {core_x1_out[7]}]
set_max_fanout 4 [get_ports {core_x1_out[6]}]
set_max_fanout 4 [get_ports {core_x1_out[5]}]
set_max_fanout 4 [get_ports {core_x1_out[4]}]
set_max_fanout 4 [get_ports {core_x1_out[3]}]
set_max_fanout 4 [get_ports {core_x1_out[2]}]
set_max_fanout 4 [get_ports {core_x1_out[1]}]
set_max_fanout 4 [get_ports {core_x1_out[0]}]
set_max_fanout 4 [get_ports {x0_addr[6]}]
set_max_fanout 4 [get_ports {x0_addr[5]}]
set_max_fanout 4 [get_ports {x0_addr[4]}]
set_max_fanout 4 [get_ports {x0_addr[3]}]
set_max_fanout 4 [get_ports {x0_addr[2]}]
set_max_fanout 4 [get_ports {x0_addr[1]}]
set_max_fanout 4 [get_ports {x0_addr[0]}]
set_max_fanout 4 [get_ports {x1_addr[6]}]
set_max_fanout 4 [get_ports {x1_addr[5]}]
set_max_fanout 4 [get_ports {x1_addr[4]}]
set_max_fanout 4 [get_ports {x1_addr[3]}]
set_max_fanout 4 [get_ports {x1_addr[2]}]
set_max_fanout 4 [get_ports {x1_addr[1]}]
set_max_fanout 4 [get_ports {x1_addr[0]}]
set_max_fanout 4 [get_ports {w_addr[5]}]
set_max_fanout 4 [get_ports {w_addr[4]}]
set_max_fanout 4 [get_ports {w_addr[3]}]
set_max_fanout 4 [get_ports {w_addr[2]}]
set_max_fanout 4 [get_ports {w_addr[1]}]
set_max_fanout 4 [get_ports {w_addr[0]}]
create_clock [get_ports clk]  -period 2  -waveform {0 1}
set_clock_uncertainty 0  [get_clocks clk]
set_clock_transition -max -rise 0.05 [get_clocks clk]
set_clock_transition -max -fall 0.05 [get_clocks clk]
set_clock_transition -min -rise 0.05 [get_clocks clk]
set_clock_transition -min -fall 0.05 [get_clocks clk]
set_input_delay -clock clk  0.1  [get_ports rstn]
set_input_delay -clock clk  0.1  [get_ports start]
set_input_delay -clock clk  0.1  [get_ports {data_dout[15]}]
set_input_delay -clock clk  0.1  [get_ports {data_dout[14]}]
set_input_delay -clock clk  0.1  [get_ports {data_dout[13]}]
set_input_delay -clock clk  0.1  [get_ports {data_dout[12]}]
set_input_delay -clock clk  0.1  [get_ports {data_dout[11]}]
set_input_delay -clock clk  0.1  [get_ports {data_dout[10]}]
set_input_delay -clock clk  0.1  [get_ports {data_dout[9]}]
set_input_delay -clock clk  0.1  [get_ports {data_dout[8]}]
set_input_delay -clock clk  0.1  [get_ports {data_dout[7]}]
set_input_delay -clock clk  0.1  [get_ports {data_dout[6]}]
set_input_delay -clock clk  0.1  [get_ports {data_dout[5]}]
set_input_delay -clock clk  0.1  [get_ports {data_dout[4]}]
set_input_delay -clock clk  0.1  [get_ports {data_dout[3]}]
set_input_delay -clock clk  0.1  [get_ports {data_dout[2]}]
set_input_delay -clock clk  0.1  [get_ports {data_dout[1]}]
set_input_delay -clock clk  0.1  [get_ports {data_dout[0]}]
set_input_delay -clock clk  0.1  [get_ports {tw_dout[15]}]
set_input_delay -clock clk  0.1  [get_ports {tw_dout[14]}]
set_input_delay -clock clk  0.1  [get_ports {tw_dout[13]}]
set_input_delay -clock clk  0.1  [get_ports {tw_dout[12]}]
set_input_delay -clock clk  0.1  [get_ports {tw_dout[11]}]
set_input_delay -clock clk  0.1  [get_ports {tw_dout[10]}]
set_input_delay -clock clk  0.1  [get_ports {tw_dout[9]}]
set_input_delay -clock clk  0.1  [get_ports {tw_dout[8]}]
set_input_delay -clock clk  0.1  [get_ports {tw_dout[7]}]
set_input_delay -clock clk  0.1  [get_ports {tw_dout[6]}]
set_input_delay -clock clk  0.1  [get_ports {tw_dout[5]}]
set_input_delay -clock clk  0.1  [get_ports {tw_dout[4]}]
set_input_delay -clock clk  0.1  [get_ports {tw_dout[3]}]
set_input_delay -clock clk  0.1  [get_ports {tw_dout[2]}]
set_input_delay -clock clk  0.1  [get_ports {tw_dout[1]}]
set_input_delay -clock clk  0.1  [get_ports {tw_dout[0]}]
set_input_delay -clock clk  0.1  [get_ports core_done]
set_input_delay -clock clk  0.1  [get_ports {core_x0_out[15]}]
set_input_delay -clock clk  0.1  [get_ports {core_x0_out[14]}]
set_input_delay -clock clk  0.1  [get_ports {core_x0_out[13]}]
set_input_delay -clock clk  0.1  [get_ports {core_x0_out[12]}]
set_input_delay -clock clk  0.1  [get_ports {core_x0_out[11]}]
set_input_delay -clock clk  0.1  [get_ports {core_x0_out[10]}]
set_input_delay -clock clk  0.1  [get_ports {core_x0_out[9]}]
set_input_delay -clock clk  0.1  [get_ports {core_x0_out[8]}]
set_input_delay -clock clk  0.1  [get_ports {core_x0_out[7]}]
set_input_delay -clock clk  0.1  [get_ports {core_x0_out[6]}]
set_input_delay -clock clk  0.1  [get_ports {core_x0_out[5]}]
set_input_delay -clock clk  0.1  [get_ports {core_x0_out[4]}]
set_input_delay -clock clk  0.1  [get_ports {core_x0_out[3]}]
set_input_delay -clock clk  0.1  [get_ports {core_x0_out[2]}]
set_input_delay -clock clk  0.1  [get_ports {core_x0_out[1]}]
set_input_delay -clock clk  0.1  [get_ports {core_x0_out[0]}]
set_input_delay -clock clk  0.1  [get_ports {core_x1_out[15]}]
set_input_delay -clock clk  0.1  [get_ports {core_x1_out[14]}]
set_input_delay -clock clk  0.1  [get_ports {core_x1_out[13]}]
set_input_delay -clock clk  0.1  [get_ports {core_x1_out[12]}]
set_input_delay -clock clk  0.1  [get_ports {core_x1_out[11]}]
set_input_delay -clock clk  0.1  [get_ports {core_x1_out[10]}]
set_input_delay -clock clk  0.1  [get_ports {core_x1_out[9]}]
set_input_delay -clock clk  0.1  [get_ports {core_x1_out[8]}]
set_input_delay -clock clk  0.1  [get_ports {core_x1_out[7]}]
set_input_delay -clock clk  0.1  [get_ports {core_x1_out[6]}]
set_input_delay -clock clk  0.1  [get_ports {core_x1_out[5]}]
set_input_delay -clock clk  0.1  [get_ports {core_x1_out[4]}]
set_input_delay -clock clk  0.1  [get_ports {core_x1_out[3]}]
set_input_delay -clock clk  0.1  [get_ports {core_x1_out[2]}]
set_input_delay -clock clk  0.1  [get_ports {core_x1_out[1]}]
set_input_delay -clock clk  0.1  [get_ports {core_x1_out[0]}]
set_input_delay -clock clk  0.1  [get_ports {x0_addr[6]}]
set_input_delay -clock clk  0.1  [get_ports {x0_addr[5]}]
set_input_delay -clock clk  0.1  [get_ports {x0_addr[4]}]
set_input_delay -clock clk  0.1  [get_ports {x0_addr[3]}]
set_input_delay -clock clk  0.1  [get_ports {x0_addr[2]}]
set_input_delay -clock clk  0.1  [get_ports {x0_addr[1]}]
set_input_delay -clock clk  0.1  [get_ports {x0_addr[0]}]
set_input_delay -clock clk  0.1  [get_ports {x1_addr[6]}]
set_input_delay -clock clk  0.1  [get_ports {x1_addr[5]}]
set_input_delay -clock clk  0.1  [get_ports {x1_addr[4]}]
set_input_delay -clock clk  0.1  [get_ports {x1_addr[3]}]
set_input_delay -clock clk  0.1  [get_ports {x1_addr[2]}]
set_input_delay -clock clk  0.1  [get_ports {x1_addr[1]}]
set_input_delay -clock clk  0.1  [get_ports {x1_addr[0]}]
set_input_delay -clock clk  0.1  [get_ports {w_addr[5]}]
set_input_delay -clock clk  0.1  [get_ports {w_addr[4]}]
set_input_delay -clock clk  0.1  [get_ports {w_addr[3]}]
set_input_delay -clock clk  0.1  [get_ports {w_addr[2]}]
set_input_delay -clock clk  0.1  [get_ports {w_addr[1]}]
set_input_delay -clock clk  0.1  [get_ports {w_addr[0]}]
set_output_delay -clock clk  0.05  [get_ports core_start]
set_output_delay -clock clk  0.05  [get_ports {core_x0[15]}]
set_output_delay -clock clk  0.05  [get_ports {core_x0[14]}]
set_output_delay -clock clk  0.05  [get_ports {core_x0[13]}]
set_output_delay -clock clk  0.05  [get_ports {core_x0[12]}]
set_output_delay -clock clk  0.05  [get_ports {core_x0[11]}]
set_output_delay -clock clk  0.05  [get_ports {core_x0[10]}]
set_output_delay -clock clk  0.05  [get_ports {core_x0[9]}]
set_output_delay -clock clk  0.05  [get_ports {core_x0[8]}]
set_output_delay -clock clk  0.05  [get_ports {core_x0[7]}]
set_output_delay -clock clk  0.05  [get_ports {core_x0[6]}]
set_output_delay -clock clk  0.05  [get_ports {core_x0[5]}]
set_output_delay -clock clk  0.05  [get_ports {core_x0[4]}]
set_output_delay -clock clk  0.05  [get_ports {core_x0[3]}]
set_output_delay -clock clk  0.05  [get_ports {core_x0[2]}]
set_output_delay -clock clk  0.05  [get_ports {core_x0[1]}]
set_output_delay -clock clk  0.05  [get_ports {core_x0[0]}]
set_output_delay -clock clk  0.05  [get_ports {core_x1[15]}]
set_output_delay -clock clk  0.05  [get_ports {core_x1[14]}]
set_output_delay -clock clk  0.05  [get_ports {core_x1[13]}]
set_output_delay -clock clk  0.05  [get_ports {core_x1[12]}]
set_output_delay -clock clk  0.05  [get_ports {core_x1[11]}]
set_output_delay -clock clk  0.05  [get_ports {core_x1[10]}]
set_output_delay -clock clk  0.05  [get_ports {core_x1[9]}]
set_output_delay -clock clk  0.05  [get_ports {core_x1[8]}]
set_output_delay -clock clk  0.05  [get_ports {core_x1[7]}]
set_output_delay -clock clk  0.05  [get_ports {core_x1[6]}]
set_output_delay -clock clk  0.05  [get_ports {core_x1[5]}]
set_output_delay -clock clk  0.05  [get_ports {core_x1[4]}]
set_output_delay -clock clk  0.05  [get_ports {core_x1[3]}]
set_output_delay -clock clk  0.05  [get_ports {core_x1[2]}]
set_output_delay -clock clk  0.05  [get_ports {core_x1[1]}]
set_output_delay -clock clk  0.05  [get_ports {core_x1[0]}]
set_output_delay -clock clk  0.05  [get_ports {core_w[15]}]
set_output_delay -clock clk  0.05  [get_ports {core_w[14]}]
set_output_delay -clock clk  0.05  [get_ports {core_w[13]}]
set_output_delay -clock clk  0.05  [get_ports {core_w[12]}]
set_output_delay -clock clk  0.05  [get_ports {core_w[11]}]
set_output_delay -clock clk  0.05  [get_ports {core_w[10]}]
set_output_delay -clock clk  0.05  [get_ports {core_w[9]}]
set_output_delay -clock clk  0.05  [get_ports {core_w[8]}]
set_output_delay -clock clk  0.05  [get_ports {core_w[7]}]
set_output_delay -clock clk  0.05  [get_ports {core_w[6]}]
set_output_delay -clock clk  0.05  [get_ports {core_w[5]}]
set_output_delay -clock clk  0.05  [get_ports {core_w[4]}]
set_output_delay -clock clk  0.05  [get_ports {core_w[3]}]
set_output_delay -clock clk  0.05  [get_ports {core_w[2]}]
set_output_delay -clock clk  0.05  [get_ports {core_w[1]}]
set_output_delay -clock clk  0.05  [get_ports {core_w[0]}]
set_output_delay -clock clk  0.05  [get_ports {stage[2]}]
set_output_delay -clock clk  0.05  [get_ports {stage[1]}]
set_output_delay -clock clk  0.05  [get_ports {stage[0]}]
set_output_delay -clock clk  0.05  [get_ports {group[5]}]
set_output_delay -clock clk  0.05  [get_ports {group[4]}]
set_output_delay -clock clk  0.05  [get_ports {group[3]}]
set_output_delay -clock clk  0.05  [get_ports {group[2]}]
set_output_delay -clock clk  0.05  [get_ports {group[1]}]
set_output_delay -clock clk  0.05  [get_ports {group[0]}]
set_output_delay -clock clk  0.05  [get_ports {bfly[5]}]
set_output_delay -clock clk  0.05  [get_ports {bfly[4]}]
set_output_delay -clock clk  0.05  [get_ports {bfly[3]}]
set_output_delay -clock clk  0.05  [get_ports {bfly[2]}]
set_output_delay -clock clk  0.05  [get_ports {bfly[1]}]
set_output_delay -clock clk  0.05  [get_ports {bfly[0]}]
set_output_delay -clock clk  0.05  [get_ports data_cen]
set_output_delay -clock clk  0.05  [get_ports data_wen]
set_output_delay -clock clk  0.05  [get_ports {data_addr[6]}]
set_output_delay -clock clk  0.05  [get_ports {data_addr[5]}]
set_output_delay -clock clk  0.05  [get_ports {data_addr[4]}]
set_output_delay -clock clk  0.05  [get_ports {data_addr[3]}]
set_output_delay -clock clk  0.05  [get_ports {data_addr[2]}]
set_output_delay -clock clk  0.05  [get_ports {data_addr[1]}]
set_output_delay -clock clk  0.05  [get_ports {data_addr[0]}]
set_output_delay -clock clk  0.05  [get_ports {data_din[15]}]
set_output_delay -clock clk  0.05  [get_ports {data_din[14]}]
set_output_delay -clock clk  0.05  [get_ports {data_din[13]}]
set_output_delay -clock clk  0.05  [get_ports {data_din[12]}]
set_output_delay -clock clk  0.05  [get_ports {data_din[11]}]
set_output_delay -clock clk  0.05  [get_ports {data_din[10]}]
set_output_delay -clock clk  0.05  [get_ports {data_din[9]}]
set_output_delay -clock clk  0.05  [get_ports {data_din[8]}]
set_output_delay -clock clk  0.05  [get_ports {data_din[7]}]
set_output_delay -clock clk  0.05  [get_ports {data_din[6]}]
set_output_delay -clock clk  0.05  [get_ports {data_din[5]}]
set_output_delay -clock clk  0.05  [get_ports {data_din[4]}]
set_output_delay -clock clk  0.05  [get_ports {data_din[3]}]
set_output_delay -clock clk  0.05  [get_ports {data_din[2]}]
set_output_delay -clock clk  0.05  [get_ports {data_din[1]}]
set_output_delay -clock clk  0.05  [get_ports {data_din[0]}]
set_output_delay -clock clk  0.05  [get_ports tw_cen]
set_output_delay -clock clk  0.05  [get_ports {tw_addr[5]}]
set_output_delay -clock clk  0.05  [get_ports {tw_addr[4]}]
set_output_delay -clock clk  0.05  [get_ports {tw_addr[3]}]
set_output_delay -clock clk  0.05  [get_ports {tw_addr[2]}]
set_output_delay -clock clk  0.05  [get_ports {tw_addr[1]}]
set_output_delay -clock clk  0.05  [get_ports {tw_addr[0]}]
set_output_delay -clock clk  0.05  [get_ports sram_tb_sel]
set_output_delay -clock clk  0.05  [get_ports busy]
set_output_delay -clock clk  0.05  [get_ports done]
