// -------------------------------------------------------------
// 
// File Name: C:\Users\darsh\Documents\Columbia PDFs\Textbooks and materials\Adv Digital EECS6321\FFT\FFT_chipathon\MATLAB\codegen\myTop\hdlsrc\mySub.v
// Created: 2026-07-03 17:42:56
// 
// Generated by MATLAB 25.1, MATLAB Coder 25.1 and HDL Coder 25.1
// 
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: mySub
// Source Path: 
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module mySub
          (a,
           b,
           y);


  input   signed [15:0] a;  // int16
  input   signed [15:0] b;  // int16
  output  signed [15:0] y;  // int16


  wire signed [16:0] p0y_sub_temp;  // sfix17
  wire signed [16:0] p0y_1;  // sfix17
  wire signed [16:0] p0y_2;  // sfix17


  assign p0y_1 = {a[15], a};
  assign p0y_2 = {b[15], b};
  assign p0y_sub_temp = p0y_1 - p0y_2;
  assign y = ((p0y_sub_temp[16] == 1'b0) && (p0y_sub_temp[15] != 1'b0) ? 16'sb0111111111111111 :
              ((p0y_sub_temp[16] == 1'b1) && (p0y_sub_temp[15] != 1'b1) ? 16'sb1000000000000000 :
              $signed(p0y_sub_temp[15:0])));

endmodule  // mySub

