// -------------------------------------------------------------
// 
// File Name: C:\Users\darsh\Documents\Columbia PDFs\Textbooks and materials\Adv Digital EECS6321\FFT\FFT_chipathon\MATLAB\codegen\myTop\hdlsrc\myTop.v
// Created: 2026-07-03 17:42:56
// 
// Generated by MATLAB 25.1, MATLAB Coder 25.1 and HDL Coder 25.1
// 
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Design base rate: 1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: myTop
// Source Path: myTop
// Hierarchy Level: 0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module myTop
          (a,
           b,
           addOut,
           subOut);


  input   signed [15:0] a;  // int16
  input   signed [15:0] b;  // int16
  output  signed [15:0] addOut;  // int16
  output  signed [15:0] subOut;  // int16




  myAdder u_myAdder (.a(a),  // int16
                     .b(b),  // int16
                     .y(addOut)  // int16
                     );

  mySub u_mySub (.a(a),  // int16
                 .b(b),  // int16
                 .y(subOut)  // int16
                 );

endmodule  // myTop

