###################################################################

# Created by write_sdc on Sat Jun 27 21:31:24 2026

###################################################################
set sdc_version 2.1

set_units -time ns -resistance kOhm -capacitance pF -voltage V -current mA
set_max_fanout 4 [current_design]
set_driving_cell -lib_cell INVD0 [get_ports clk]
set_driving_cell -lib_cell INVD0 [get_ports tb_sel]
set_driving_cell -lib_cell INVD0 [get_ports tb_cen]
set_driving_cell -lib_cell INVD0 [get_ports tb_wen]
set_driving_cell -lib_cell INVD0 [get_ports {tb_addr[6]}]
set_driving_cell -lib_cell INVD0 [get_ports {tb_addr[5]}]
set_driving_cell -lib_cell INVD0 [get_ports {tb_addr[4]}]
set_driving_cell -lib_cell INVD0 [get_ports {tb_addr[3]}]
set_driving_cell -lib_cell INVD0 [get_ports {tb_addr[2]}]
set_driving_cell -lib_cell INVD0 [get_ports {tb_addr[1]}]
set_driving_cell -lib_cell INVD0 [get_ports {tb_addr[0]}]
set_driving_cell -lib_cell INVD0 [get_ports {tb_din[15]}]
set_driving_cell -lib_cell INVD0 [get_ports {tb_din[14]}]
set_driving_cell -lib_cell INVD0 [get_ports {tb_din[13]}]
set_driving_cell -lib_cell INVD0 [get_ports {tb_din[12]}]
set_driving_cell -lib_cell INVD0 [get_ports {tb_din[11]}]
set_driving_cell -lib_cell INVD0 [get_ports {tb_din[10]}]
set_driving_cell -lib_cell INVD0 [get_ports {tb_din[9]}]
set_driving_cell -lib_cell INVD0 [get_ports {tb_din[8]}]
set_driving_cell -lib_cell INVD0 [get_ports {tb_din[7]}]
set_driving_cell -lib_cell INVD0 [get_ports {tb_din[6]}]
set_driving_cell -lib_cell INVD0 [get_ports {tb_din[5]}]
set_driving_cell -lib_cell INVD0 [get_ports {tb_din[4]}]
set_driving_cell -lib_cell INVD0 [get_ports {tb_din[3]}]
set_driving_cell -lib_cell INVD0 [get_ports {tb_din[2]}]
set_driving_cell -lib_cell INVD0 [get_ports {tb_din[1]}]
set_driving_cell -lib_cell INVD0 [get_ports {tb_din[0]}]
set_driving_cell -lib_cell INVD0 [get_ports core_cen]
set_driving_cell -lib_cell INVD0 [get_ports core_wen]
set_driving_cell -lib_cell INVD0 [get_ports {core_addr[6]}]
set_driving_cell -lib_cell INVD0 [get_ports {core_addr[5]}]
set_driving_cell -lib_cell INVD0 [get_ports {core_addr[4]}]
set_driving_cell -lib_cell INVD0 [get_ports {core_addr[3]}]
set_driving_cell -lib_cell INVD0 [get_ports {core_addr[2]}]
set_driving_cell -lib_cell INVD0 [get_ports {core_addr[1]}]
set_driving_cell -lib_cell INVD0 [get_ports {core_addr[0]}]
set_driving_cell -lib_cell INVD0 [get_ports {core_din[15]}]
set_driving_cell -lib_cell INVD0 [get_ports {core_din[14]}]
set_driving_cell -lib_cell INVD0 [get_ports {core_din[13]}]
set_driving_cell -lib_cell INVD0 [get_ports {core_din[12]}]
set_driving_cell -lib_cell INVD0 [get_ports {core_din[11]}]
set_driving_cell -lib_cell INVD0 [get_ports {core_din[10]}]
set_driving_cell -lib_cell INVD0 [get_ports {core_din[9]}]
set_driving_cell -lib_cell INVD0 [get_ports {core_din[8]}]
set_driving_cell -lib_cell INVD0 [get_ports {core_din[7]}]
set_driving_cell -lib_cell INVD0 [get_ports {core_din[6]}]
set_driving_cell -lib_cell INVD0 [get_ports {core_din[5]}]
set_driving_cell -lib_cell INVD0 [get_ports {core_din[4]}]
set_driving_cell -lib_cell INVD0 [get_ports {core_din[3]}]
set_driving_cell -lib_cell INVD0 [get_ports {core_din[2]}]
set_driving_cell -lib_cell INVD0 [get_ports {core_din[1]}]
set_driving_cell -lib_cell INVD0 [get_ports {core_din[0]}]
set_load -pin_load 0.005 [get_ports {dout[15]}]
set_load -pin_load 0.005 [get_ports {dout[14]}]
set_load -pin_load 0.005 [get_ports {dout[13]}]
set_load -pin_load 0.005 [get_ports {dout[12]}]
set_load -pin_load 0.005 [get_ports {dout[11]}]
set_load -pin_load 0.005 [get_ports {dout[10]}]
set_load -pin_load 0.005 [get_ports {dout[9]}]
set_load -pin_load 0.005 [get_ports {dout[8]}]
set_load -pin_load 0.005 [get_ports {dout[7]}]
set_load -pin_load 0.005 [get_ports {dout[6]}]
set_load -pin_load 0.005 [get_ports {dout[5]}]
set_load -pin_load 0.005 [get_ports {dout[4]}]
set_load -pin_load 0.005 [get_ports {dout[3]}]
set_load -pin_load 0.005 [get_ports {dout[2]}]
set_load -pin_load 0.005 [get_ports {dout[1]}]
set_load -pin_load 0.005 [get_ports {dout[0]}]
set_max_capacitance 0.005 [get_ports clk]
set_max_capacitance 0.005 [get_ports tb_sel]
set_max_capacitance 0.005 [get_ports tb_cen]
set_max_capacitance 0.005 [get_ports tb_wen]
set_max_capacitance 0.005 [get_ports {tb_addr[6]}]
set_max_capacitance 0.005 [get_ports {tb_addr[5]}]
set_max_capacitance 0.005 [get_ports {tb_addr[4]}]
set_max_capacitance 0.005 [get_ports {tb_addr[3]}]
set_max_capacitance 0.005 [get_ports {tb_addr[2]}]
set_max_capacitance 0.005 [get_ports {tb_addr[1]}]
set_max_capacitance 0.005 [get_ports {tb_addr[0]}]
set_max_capacitance 0.005 [get_ports {tb_din[15]}]
set_max_capacitance 0.005 [get_ports {tb_din[14]}]
set_max_capacitance 0.005 [get_ports {tb_din[13]}]
set_max_capacitance 0.005 [get_ports {tb_din[12]}]
set_max_capacitance 0.005 [get_ports {tb_din[11]}]
set_max_capacitance 0.005 [get_ports {tb_din[10]}]
set_max_capacitance 0.005 [get_ports {tb_din[9]}]
set_max_capacitance 0.005 [get_ports {tb_din[8]}]
set_max_capacitance 0.005 [get_ports {tb_din[7]}]
set_max_capacitance 0.005 [get_ports {tb_din[6]}]
set_max_capacitance 0.005 [get_ports {tb_din[5]}]
set_max_capacitance 0.005 [get_ports {tb_din[4]}]
set_max_capacitance 0.005 [get_ports {tb_din[3]}]
set_max_capacitance 0.005 [get_ports {tb_din[2]}]
set_max_capacitance 0.005 [get_ports {tb_din[1]}]
set_max_capacitance 0.005 [get_ports {tb_din[0]}]
set_max_capacitance 0.005 [get_ports core_cen]
set_max_capacitance 0.005 [get_ports core_wen]
set_max_capacitance 0.005 [get_ports {core_addr[6]}]
set_max_capacitance 0.005 [get_ports {core_addr[5]}]
set_max_capacitance 0.005 [get_ports {core_addr[4]}]
set_max_capacitance 0.005 [get_ports {core_addr[3]}]
set_max_capacitance 0.005 [get_ports {core_addr[2]}]
set_max_capacitance 0.005 [get_ports {core_addr[1]}]
set_max_capacitance 0.005 [get_ports {core_addr[0]}]
set_max_capacitance 0.005 [get_ports {core_din[15]}]
set_max_capacitance 0.005 [get_ports {core_din[14]}]
set_max_capacitance 0.005 [get_ports {core_din[13]}]
set_max_capacitance 0.005 [get_ports {core_din[12]}]
set_max_capacitance 0.005 [get_ports {core_din[11]}]
set_max_capacitance 0.005 [get_ports {core_din[10]}]
set_max_capacitance 0.005 [get_ports {core_din[9]}]
set_max_capacitance 0.005 [get_ports {core_din[8]}]
set_max_capacitance 0.005 [get_ports {core_din[7]}]
set_max_capacitance 0.005 [get_ports {core_din[6]}]
set_max_capacitance 0.005 [get_ports {core_din[5]}]
set_max_capacitance 0.005 [get_ports {core_din[4]}]
set_max_capacitance 0.005 [get_ports {core_din[3]}]
set_max_capacitance 0.005 [get_ports {core_din[2]}]
set_max_capacitance 0.005 [get_ports {core_din[1]}]
set_max_capacitance 0.005 [get_ports {core_din[0]}]
set_max_fanout 4 [get_ports clk]
set_max_fanout 4 [get_ports tb_sel]
set_max_fanout 4 [get_ports tb_cen]
set_max_fanout 4 [get_ports tb_wen]
set_max_fanout 4 [get_ports {tb_addr[6]}]
set_max_fanout 4 [get_ports {tb_addr[5]}]
set_max_fanout 4 [get_ports {tb_addr[4]}]
set_max_fanout 4 [get_ports {tb_addr[3]}]
set_max_fanout 4 [get_ports {tb_addr[2]}]
set_max_fanout 4 [get_ports {tb_addr[1]}]
set_max_fanout 4 [get_ports {tb_addr[0]}]
set_max_fanout 4 [get_ports {tb_din[15]}]
set_max_fanout 4 [get_ports {tb_din[14]}]
set_max_fanout 4 [get_ports {tb_din[13]}]
set_max_fanout 4 [get_ports {tb_din[12]}]
set_max_fanout 4 [get_ports {tb_din[11]}]
set_max_fanout 4 [get_ports {tb_din[10]}]
set_max_fanout 4 [get_ports {tb_din[9]}]
set_max_fanout 4 [get_ports {tb_din[8]}]
set_max_fanout 4 [get_ports {tb_din[7]}]
set_max_fanout 4 [get_ports {tb_din[6]}]
set_max_fanout 4 [get_ports {tb_din[5]}]
set_max_fanout 4 [get_ports {tb_din[4]}]
set_max_fanout 4 [get_ports {tb_din[3]}]
set_max_fanout 4 [get_ports {tb_din[2]}]
set_max_fanout 4 [get_ports {tb_din[1]}]
set_max_fanout 4 [get_ports {tb_din[0]}]
set_max_fanout 4 [get_ports core_cen]
set_max_fanout 4 [get_ports core_wen]
set_max_fanout 4 [get_ports {core_addr[6]}]
set_max_fanout 4 [get_ports {core_addr[5]}]
set_max_fanout 4 [get_ports {core_addr[4]}]
set_max_fanout 4 [get_ports {core_addr[3]}]
set_max_fanout 4 [get_ports {core_addr[2]}]
set_max_fanout 4 [get_ports {core_addr[1]}]
set_max_fanout 4 [get_ports {core_addr[0]}]
set_max_fanout 4 [get_ports {core_din[15]}]
set_max_fanout 4 [get_ports {core_din[14]}]
set_max_fanout 4 [get_ports {core_din[13]}]
set_max_fanout 4 [get_ports {core_din[12]}]
set_max_fanout 4 [get_ports {core_din[11]}]
set_max_fanout 4 [get_ports {core_din[10]}]
set_max_fanout 4 [get_ports {core_din[9]}]
set_max_fanout 4 [get_ports {core_din[8]}]
set_max_fanout 4 [get_ports {core_din[7]}]
set_max_fanout 4 [get_ports {core_din[6]}]
set_max_fanout 4 [get_ports {core_din[5]}]
set_max_fanout 4 [get_ports {core_din[4]}]
set_max_fanout 4 [get_ports {core_din[3]}]
set_max_fanout 4 [get_ports {core_din[2]}]
set_max_fanout 4 [get_ports {core_din[1]}]
set_max_fanout 4 [get_ports {core_din[0]}]
create_clock [get_ports clk]  -period 2  -waveform {0 1}
set_clock_uncertainty 0  [get_clocks clk]
set_clock_transition -max -rise 0.05 [get_clocks clk]
set_clock_transition -max -fall 0.05 [get_clocks clk]
set_clock_transition -min -rise 0.05 [get_clocks clk]
set_clock_transition -min -fall 0.05 [get_clocks clk]
set_input_delay -clock clk  0.1  [get_ports tb_sel]
set_input_delay -clock clk  0.1  [get_ports tb_cen]
set_input_delay -clock clk  0.1  [get_ports tb_wen]
set_input_delay -clock clk  0.1  [get_ports {tb_addr[6]}]
set_input_delay -clock clk  0.1  [get_ports {tb_addr[5]}]
set_input_delay -clock clk  0.1  [get_ports {tb_addr[4]}]
set_input_delay -clock clk  0.1  [get_ports {tb_addr[3]}]
set_input_delay -clock clk  0.1  [get_ports {tb_addr[2]}]
set_input_delay -clock clk  0.1  [get_ports {tb_addr[1]}]
set_input_delay -clock clk  0.1  [get_ports {tb_addr[0]}]
set_input_delay -clock clk  0.1  [get_ports {tb_din[15]}]
set_input_delay -clock clk  0.1  [get_ports {tb_din[14]}]
set_input_delay -clock clk  0.1  [get_ports {tb_din[13]}]
set_input_delay -clock clk  0.1  [get_ports {tb_din[12]}]
set_input_delay -clock clk  0.1  [get_ports {tb_din[11]}]
set_input_delay -clock clk  0.1  [get_ports {tb_din[10]}]
set_input_delay -clock clk  0.1  [get_ports {tb_din[9]}]
set_input_delay -clock clk  0.1  [get_ports {tb_din[8]}]
set_input_delay -clock clk  0.1  [get_ports {tb_din[7]}]
set_input_delay -clock clk  0.1  [get_ports {tb_din[6]}]
set_input_delay -clock clk  0.1  [get_ports {tb_din[5]}]
set_input_delay -clock clk  0.1  [get_ports {tb_din[4]}]
set_input_delay -clock clk  0.1  [get_ports {tb_din[3]}]
set_input_delay -clock clk  0.1  [get_ports {tb_din[2]}]
set_input_delay -clock clk  0.1  [get_ports {tb_din[1]}]
set_input_delay -clock clk  0.1  [get_ports {tb_din[0]}]
set_input_delay -clock clk  0.1  [get_ports core_cen]
set_input_delay -clock clk  0.1  [get_ports core_wen]
set_input_delay -clock clk  0.1  [get_ports {core_addr[6]}]
set_input_delay -clock clk  0.1  [get_ports {core_addr[5]}]
set_input_delay -clock clk  0.1  [get_ports {core_addr[4]}]
set_input_delay -clock clk  0.1  [get_ports {core_addr[3]}]
set_input_delay -clock clk  0.1  [get_ports {core_addr[2]}]
set_input_delay -clock clk  0.1  [get_ports {core_addr[1]}]
set_input_delay -clock clk  0.1  [get_ports {core_addr[0]}]
set_input_delay -clock clk  0.1  [get_ports {core_din[15]}]
set_input_delay -clock clk  0.1  [get_ports {core_din[14]}]
set_input_delay -clock clk  0.1  [get_ports {core_din[13]}]
set_input_delay -clock clk  0.1  [get_ports {core_din[12]}]
set_input_delay -clock clk  0.1  [get_ports {core_din[11]}]
set_input_delay -clock clk  0.1  [get_ports {core_din[10]}]
set_input_delay -clock clk  0.1  [get_ports {core_din[9]}]
set_input_delay -clock clk  0.1  [get_ports {core_din[8]}]
set_input_delay -clock clk  0.1  [get_ports {core_din[7]}]
set_input_delay -clock clk  0.1  [get_ports {core_din[6]}]
set_input_delay -clock clk  0.1  [get_ports {core_din[5]}]
set_input_delay -clock clk  0.1  [get_ports {core_din[4]}]
set_input_delay -clock clk  0.1  [get_ports {core_din[3]}]
set_input_delay -clock clk  0.1  [get_ports {core_din[2]}]
set_input_delay -clock clk  0.1  [get_ports {core_din[1]}]
set_input_delay -clock clk  0.1  [get_ports {core_din[0]}]
set_output_delay -clock clk  0.05  [get_ports {dout[15]}]
set_output_delay -clock clk  0.05  [get_ports {dout[14]}]
set_output_delay -clock clk  0.05  [get_ports {dout[13]}]
set_output_delay -clock clk  0.05  [get_ports {dout[12]}]
set_output_delay -clock clk  0.05  [get_ports {dout[11]}]
set_output_delay -clock clk  0.05  [get_ports {dout[10]}]
set_output_delay -clock clk  0.05  [get_ports {dout[9]}]
set_output_delay -clock clk  0.05  [get_ports {dout[8]}]
set_output_delay -clock clk  0.05  [get_ports {dout[7]}]
set_output_delay -clock clk  0.05  [get_ports {dout[6]}]
set_output_delay -clock clk  0.05  [get_ports {dout[5]}]
set_output_delay -clock clk  0.05  [get_ports {dout[4]}]
set_output_delay -clock clk  0.05  [get_ports {dout[3]}]
set_output_delay -clock clk  0.05  [get_ports {dout[2]}]
set_output_delay -clock clk  0.05  [get_ports {dout[1]}]
set_output_delay -clock clk  0.05  [get_ports {dout[0]}]
